### ISSUE TITLE
ObjectID.isValid seems to accept a lot of things.

### ISSUE THREAD

**Issue by tolmasky** [mongodb/js-bson#113]
From the code, it seems that if you pass it a string that is 12 characters long, it returns true regardless (not checking for hexness):

isValid("export-test1") // return true. Expected behavior? Only 24 char strings need to be hex?

In fact, due to the fact that 12 and 24 length non-numbers are allowed, but then only 24 length thing are hex checked if its 24 long, strange things like this also pass:

isValid(function(a,b,c,d,e,f,g,h,i,j,k,l){}) // returns true because func.length == 12

and of course:

isValid({length:12}) // return true

**Comment by christkv** [comment]
yes it accept a 12 byte string of everything.

http://mongodb.github.io/node-mongodb-native/2.0/tutorials/objectid/

**Comment by tolmasky** [comment]
Theres no desire to fix the strange behavior when passing in non strings ( a common occurrence in a non strict language)?

**Comment by christkv** [comment]
this will not be fixed as it's actually a valid string from the perspective of an ObjectId generation.

**Comment by tolmasky** [comment]
I understand that 12 char strings should work, but I'm referring to the second and third examples I gave:

```javascript
isValid({length:12}) // returns true
```

```javascript
isValid(function(a,b,c,d,e,f,g,h,i,j,k,l){}) // returns true because func.length == 12)
```

I don't believe those are meant to return true, especially considering that the tests specifically test for certain edge cases like isValid({}) (returns false).

For example:

```javascript
var myId = { length:12 };
if (ObjectId.isValid(myId)) return new ObjectId(myId);
```

This throws "Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters" even though I theoretically made sure it was fine with isValid, thats because isValid just checks that the thing has a length property === 12, then myId gets coerced into a string [Object object].

A more interesting example is the following:

```javascript
var bytes = ["1","2","3","4","5","6","a","b","c","d","e","f"]
if (ObjectId.isValid(myId)) return new ObjectId(bytes);
```
I meant to do bytes.join(""), but forgot, but isValid incorrectly returns true since bytes.length === 12, then it gets coerced to '1,2,3,4,5,6,7,8,9,10,11,12'
