### ISSUE TITLE
(node-gyp rebuild 2> builderror.log) || (exit 0)

### ISSUE THREAD

**Issue by jsguy** [mongodb/js-bson#115]
Hi @christkv ,

When I try and install bson using nodejs v 0.12.0 on OSX 10.9.3, I get the following failure:

```shell
$ npm install bson --save
|
> bson@0.2.19 install /jsguy/misojs/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```

Any ideas?

**Comment by smartmouse** [comment]
It will help if you can attach the content in builderror.log.
Some node-modules have not fully ported to support nodejs V0.12.0. There are some deprecated functions.
One example is: child_process: customFds option is deprecated, use stdio instead.

**Comment by jsguy** [comment]
Here is the contents of builderror.log:
```
child_process: customFds option is deprecated, use stdio instead.
```

So yeah, exactly the issue you mentioned - does this mean you need to update bson, or is it nodejs?

**Comment by smartmouse** [comment]
That is only a warning for deprecation, should not affect the code., unless you saw some other errors.

Please see following on the info on this deprecation
https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12

**Comment by jsguy** [comment]
Hmm... ok.
