### ISSUE TITLE
.buffer property not documented

### ISSUE THREAD

**Issue by panuhorsmalahti** [mongodb/js-bson#117]
MongoDB's binary class has a very useful .buffer property for using the Buffer. This is not reflected in the JSDoc, which means it's not generated to the documentation here:
http://mongodb.github.io/node-mongodb-native/api-bson-generated/binary.html

It should be documented so that it's safe to use. (After that I can make a PR to the TypeScript type definition, but that's another issue).

The JSDoc is here:
https://github.com/mongodb/js-bson/blob/master/lib/bson/binary.js

**Comment by christkv** [comment]
it's considered internal state and should not be used. use the method value() instead
