### ISSUE TITLE
Gyp build fails without a warning.

### ISSUE THREAD

**Issue by IvanGoncharov** [mongodb/js-bson#118]
I spend couple hours figuring out why I have following warning:
>Failed to load c++ bson extension, using pure JS version

It's actually a very [common](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=js-bson%3a%20failed%20to%20load%20c%2b%2b%20bson%20extension%2c%20using%20pure%20js%20version) issue, but each case have different root cause(in my case it was missing "node-legacy" package).

I think real problem is that "npm install" doesn't provide any warnings or other clues.
The following line from package.json is responsible for that:
>"install" : "(node-gyp rebuild 2> builderror.log) || (exit 0)",

NPM is [explicitly discourage](https://docs.npmjs.com/misc/scripts#note-install-scripts-are-an-antipattern) such tricks. But I understand why fallback mechanism is needed.

Solution would be to extract C++ part into separate NPM package and connect it using [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) feature.

**Comment by evgeniyp** [comment]
This worked for me:

Go to the file (in your project):
'node_modules/mongoose/node_modules/mongodb/node_modules/bson/ext/index.js'
and change
bson = require('../build/Release/bson');
to
bson = require('bson');

**Comment by IvanGoncharov** [comment]
@evgeniyp 
As I wrote above, I fixed warning by installing "node-legacy" package and re-install.
It looks like you just disable C++ code, but be aware that this could lead to significant slowdown.
To find real root cause inspect "node_modules/mongoose/node_modules/mongodb/node_modules/bson/builderror.log" file.

P.S. That is exactly the point that I tried to make.
This issue is about proper error reporting, so you diagnose problem on "npm install" stage and not in runtime. Because right now warning message is very confusing and this leads to workarounds instead of fix for C++ build.

**Comment by RomanGotsiy** [comment]
I had the same warning caused by failed c++ build. NPM silence seems weird in this situation. It would be much better if at least some warning been shown.
But solution proposed by @IvanGoncharov seems very reasonable.

**Comment by Volox** [comment]
+1
same here on Windows

**Comment by christkv** [comment]
bson-ext extension moved
