### ISSUE TITLE
Can't create full text search index using '$**' wildcard 

### ISSUE THREAD

**Issue by demetriusnunes** [mongodb/js-bson#119]
According to documentation, in order to create a full-text search index on all String fields, we need to use the wild card '$**', but when doing this through the nodejs mongo driver, we get the error that the key cannot start with '$' thrown by BSON.checkKey.

http://docs.mongodb.org/manual/tutorial/create-text-index-on-multiple-fields/#index-all-fields

**Comment by christkv** [comment]
I cannot reproduce this in the 2.0 driver.

```js
/**
 * @ignore
 */
exports.shouldCorrectlyCreateTextIndex = {
  metadata: { requires: { topology: ['single', 'replicaset', 'sharded', 'ssl', 'heap', 'wiredtiger'] } },
  
  // The actual test we wish to run
  test: function(configuration, test) {
    var db = configuration.newDbInstance({w:1}, {poolSize:1});
    db.open(function(err, db) {
      db.collection('text_index').createIndex({ "$**": "text" }, { name: "TextIndex" }, function(err, r) {
        // Let's close the db
        db.close();
        test.done();
      });
    });
  }
}
```
