### ISSUE TITLE
 Failed to load c++ bson extension, using pure JS version. Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } js-bson:

### ISSUE THREAD

**Issue by masoom** [mongodb/js-bson#120]
I tried to move my project files from MAC to Windows7 and ran into this error when I run my server.js and not able to fix it. 

My current environment
node v0.12.2, NPM 2.7.4, Python 3.4, 

I have done the following till now
- Reinstalled Node & NPM
- Deleted npm cache - npm cache clean
- Installed all the modules again including mongoose, mongodb native
- Created the bson folder at node_modules\mongoose\node_modules\mongodb\node_modules\bson \ext\index.js
- removed the node_modules
- Installed and rebuild node-gyp
But nothing works

**Comment by cades** [comment]
+1

**Comment by christkv** [comment]
bson-ext done

**Comment by ymz2012** [comment]
bson = require('../build/Release/bson');
to
bson = require('bson');
