### ISSUE TITLE
Split of C++ code as bson-ext missed a node-gyp call in package.json

### ISSUE THREAD

**Issue by triccardi-systran** [mongodb/js-bson#121]
Since 6437b5294714c042ac6a62ac99d8985cbf842d07 node-gyp is not needed anymore in this node module.
However it's still called in package.json:script:install:

https://github.com/mongodb/js-bson/blob/b750f1a374f594059f2634bfc476e98623f0c9c3/package.json#L25
https://github.com/mongodb/js-bson/commit/6437b5294714c042ac6a62ac99d8985cbf842d07#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25

**Comment by christkv** [comment]
fixed
