### ISSUE TITLE
Cannot find module '././binary_parser'

### ISSUE THREAD

**Issue by cloppy** [mongodb/js-bson#122]
I'm trying to use mongoose with nwjs, but constantly get errors.

Like in `lib/bson/index.js` i.e. line 19, there is a prepending `./`. Why is that? Every module that is required already has a './' as prefix.

```javascript
[ './binary_parser'
  , './binary'
  , './code'
  , './db_ref'
  , './double'
  , './max_key'
  , './min_key'
  , './objectid'
  , './symbol'
  , './timestamp'
  , './long'].forEach(function (path) {
  	var module = require('./' + path);
  	for (var i in module) {
  		exports[i] = module[i];
    }
});
```

I am using Webpack and when those modules are required, it alwys states the error:
```
Cannot find module '././binary_parser'
```

So why is that second `./` needed?

**Comment by christkv** [comment]
I have no experience with nwjs or how it works. You might get a better answer in their support forum if there is one.

**Comment by cloppy** [comment]
I think this is more a webpack issue, since webpack is overriding the `require()` function with some additional stuff.

But is it even necessary to prefix this with an additional `./` to load?

**Comment by matwood** [comment]
I was coming here to ask the same question. I can do a fix and issue the PR if needed, but I'm not sure if the extra './' is necessary for some other environment I'm not aware of.

**Comment by christkv** [comment]
this should not be a problem anymore

**Comment by stevenlee001** [comment]
I still got the same problem on following versions:
webpack: 1.12.2
mongoose: 4.2.2
bson: 0.4.19

**Comment by VodkaBears** [comment]
> this should not be a problem anymore

Seems like the problem is still here. Webpack can't resolve paths in `lib/bson/index.js`.

```
webpack: 1.12.9
mongodb: 2.1.3
bson: 0.4.20
```
