### ISSUE TITLE
json map ording issue with BSON.deserialize

### ISSUE THREAD

**Issue by pawanpec** [mongodb/js-bson#127]
I have a document like 

 {
   "_id": ObjectId("531ee42ccf626e98e03b574c"),
   "ct": "100713219145",
   "m": {
     "50124338": "Java Developer",
     "50119482": "Tester",
     "50124295": "Systems (QA) Analyst \/ Busin *&^^ ess Analyst Uyemaom doyedld P8",
     "50124357": "Software Engineer ( Senior Applications Developer)_5 march"
  },
   "ar": "-1",
   "to": "7",
   "imp": "n",
   "st": "n",
   "rm": {
     "50124338": "homacc|-1|2-4 yrs|Ahmedabad, Bengaluru\/ Bangalore, Chennai, Delhi, Delhi\/ NCR|java,Java Eclipse ,Core Java C C++ ,Core Java XML ,Core Java Core Java , [...]",
     "50119482": "times Business solution|1.0 Lac To 5.0 Lac|1 - 5 yrs|Bengaluru\/ Bangalore, Chennai, Delhi\/ NCR, Noida\/ Greater Noida|Test Cases Test Plans",
     "50124295": "TBSL|2.0 Lac To 10.0 Lac|2-7 yrs|Chennai, Delhi, Mumbai, Pune, Guwahati|java,oracle,linux,raid,selenium,Automated Testing,Unix C++ ,Linux Shell Script [...]",
     "50124357": "homacc|-1|2-4 yrs|Ahmedabad, Bengaluru\/ Bangalore, Chennai, Delhi, Delhi\/ NCR|c++,javascript,vb,oracle,uml,linux,python,unix,xml,http"
  },
   "ui": "ankit_mishra07",
   "ms": "y",
   "rf": "n",
   "nc": NumberInt(0),
   "pn": "pncc",
   "mt": "email",
   "fo": "ja"
}	

In mongo when i go raw type doc ,i get below output which is ordered.

�_idS�,�bn��;WLm�50124338Java Developer50119482Tester50124295ASystems (QA) Analyst / Busin *&^^ ess Analyst Uyemaom doyedld P850124357;Software Engineer ( Senior Applications Developer)_5 march

But when i do BSON.deserialize(item) item which has map order is lost.

Please help.

**Comment by christkv** [comment]
I suspect you are doing this in the browser. I'm using the implicit sort order in v8 that. Unfortunately this is not a defined behavior for Javascript meaning internet explorer could very well send back the keys in the wrong order.

**Comment by publicocean0** [comment]
i have a similar problem but i have arrays .... i m sending a array to server but library seams be not able to handle it

**Comment by christkv** [comment]
without code I cannot tell you what might be going wrong. if you can create a snippet of code that reproduces it then I might be able to tell you what the problem is.

**Comment by publicocean0** [comment]
sorry i removed that code with problem .... now i use a new js library for serialization(BOP protocol)
