### ISSUE TITLE
Error wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by strigunov** [mongodb/js-bson#132]
[Error: /home/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: wrong ELF class: ELFCLASS64]
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: /home/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: wrong ELF class: ELFCLASS64]
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: /home/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: wrong ELF class: ELFCLASS64]
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: /home/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: wrong ELF class: ELFCLASS64]
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by christkv** [comment]
You need to delete node_modules and reinstall as you are having c++ binary extensions either compiled against a different os or against a different node.js version than what you are running.
