### ISSUE TITLE
undefined gets serialized to null bson type

### ISSUE THREAD

**Issue by vkarpov15** [mongodb/js-bson#134]
https://github.com/mongodb/js-bson/blob/b356ee449b83373833db40fabe1672ed39ce1630/lib/bson/parser/serializer.js#L134-143

https://github.com/mongodb/js-bson/blob/b356ee449b83373833db40fabe1672ed39ce1630/lib/bson/parser/deserializer.js#L122-125

Is it worth it to actually support the bson type undefined? It's deprecated but it looks like js-bson just doesn't use it at all. Re: https://github.com/Automattic/mongoose/issues/3169

**Comment by christkv** [comment]
no it was deprecated before I even started the driver (over 5 years ago).
