### ISSUE TITLE
ObjectId.isValid should return true when number ?

### ISSUE THREAD

**Issue by alexserver** [mongodb/js-bson#140]
I'm relying on ObjectId.isValid function to validate my ObjectID string representations.
I read that this module is widely used in mongo libraries, so for every ObjectID I'm expecting to receive a 24 hex characters string.
But when I run `ObjectId.isValid( <any number> )` this is returning true.
Here the code that does that: https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L244-L245

Shouldn't this avoid numbers as ObjectId and instead only 24 chars representations ?

**Comment by rentrop** [comment]
+1

**Comment by christkv** [comment]
this is unfortunately a backward compatibility issue that cannot be removed due to people relying on this but it basically takes a number you pass in and change it to a string (look in the constructor).
