### ISSUE TITLE
skipFields or rawFields option to increase deserialize performance

### ISSUE THREAD

**Issue by timkuijsten** [mongodb/js-bson#144]
I think it would be nice if it would be possible to pass an object containing key names that don't have to be parsed. Maybe an option named skipFields (boolean per name). Than any named field won't be parsed and would be skipped. Another way to accomplish this would be to use something like "rawFields" which does not parse, but slices and returns the raw buffer of that field.

I'm working on a patch to accomplish this, but I'd like to know if such a patch would make any chance of being merged.

Use case:
I'm using BSON to store a lot of DAGs in leveldb. The structure of the data is quite simple, every object has a small header and optionally a large document and some meta info about the document.

    {
      h: {Object}  header containing the following values:
        id:  {mixed}  id of this h
        v:   {base64 String}  version
        pa:  {Array}  parent versions
        [d]: {Boolean}  true if this id is deleted
      [m]: {Object}  meta info to store with this document
      [b]: {mixed}  document to save
    }

I serialize this whole object into BSON but I often have to traverse the DAG and so have to read out the parents (which are in h.pa). Currently I have to deserialize the whole object, including the "m" and potentially large "b" keys. Flame graphs show that  a large proportion of time in walking the tree is taken by deserializing each object. So I would like to only parse the header field in this case. Like:

    var opts = {
      skipFields = {
        m: true,
        b: true
      }
    };
    var item = BSON.deserialize(buffer, opts);
    assert(item.h);
    assert(!item.m);
    assert(!item.b);

**Comment by christkv** [comment]
Unfortunately not the only concern of this bson parser is maximum performance so people do not have to deal with installing the c++ extension.I might be worth forking instead and releasing a derivate of it under a different name (son-advanced) or something.

**Comment by christkv** [comment]
I will accept the pull request if you can prove that it does not impact raw performance.

**Comment by timkuijsten** [comment]
Personally I don't care that much about performance either, but when using bson to store trees with associated data, like in my case, the performance loss is too big and unnecessary.

I did hack up a quick unfinished (yet non-working) patch to show you the rough idea and see if it's usable at all. I will polish it and do some performance tests if it's not a direct no ;-)

**Comment by timkuijsten** [comment]
As you can see in bec0ef1 the idea is to simply add conditionals to the object[name] assignments and parsing/calculation part while maintaining the index increments. I will polish this code, *make it work* and do some performance tests if you don't think this is outright unacceptable.

**Comment by timkuijsten** [comment]
Of course another way would be to not mix in this code but just one conditional at the beginning after the name is parsed. And if that name needs to be skipped than all type based increment logic could be done in that single if as well. Performance wise this should not really matter though, just makes the diff easier to read and maybe the resulting code.

**Comment by christkv** [comment]
as long as you can keep V8 happy and avoid deoptimizations the penalty might only be very very slight. but benchmarks will prove that out anyway.

**Comment by timkuijsten** [comment]
Great, shall I cook up some benchmarks myself or do you have a suggestion where I should do them?

**Comment by christkv** [comment]
under benchmarks there is a suite file that you can modify to your hearts content. Try small, medium and big sized documents that (serialize and deserialize) using and not using skipFields. I plan to do a more extensive benchmark suite at some point but we are in the process of standardizing the tests internally at the moment.

**Comment by timkuijsten** [comment]
I did some tests[0] with the new parser that supports the skipFields option[1]. I think the results are a bit disappointing and fluctuate more than I would expect. I've used 20.000 items and repeated 5 different tests 3 times. I did this for small, medium and large sized items. This are the results:

small sized items ([~42 bytes per item](https://github.com/timkuijsten/js-bson/blob/1bc99326a2ae749c35572f4edd936677305a525b/test/node/test_skip_fields.js#L15-L16)):

    ################
    creating 20000 small items...
     : 83ms

    serialize and deserialize items, without skipFields
     : 235ms
    serialize and deserialize items, with empty skipFields
     : 202ms
    serialize and deserialize items, skip field "b"
     : 177ms
    serialize and deserialize items, skip non-existing field "a"
     : 203ms
    serialize and deserialize items, skip field "6"
     : 196ms

    serialize and deserialize items, without skipFields
     : 181ms
    serialize and deserialize items, with empty skipFields
     : 191ms
    serialize and deserialize items, skip field "b"
     : 162ms
    serialize and deserialize items, skip non-existing field "a"
     : 190ms
    serialize and deserialize items, skip field "6"
     : 184ms

    serialize and deserialize items, without skipFields
     : 182ms
    serialize and deserialize items, with empty skipFields
     : 191ms
    serialize and deserialize items, skip field "b"
     : 161ms
    serialize and deserialize items, skip non-existing field "a"
     : 197ms
    serialize and deserialize items, skip field "6"
     : 184ms

medium sized items ([~1095 bytes per item](https://github.com/timkuijsten/js-bson/blob/1bc99326a2ae749c35572f4edd936677305a525b/test/node/test_skip_fields.js#L35-L44)):

    ################
    creating 20000 medium items...
     : 196ms

    serialize and deserialize items, without skipFields
     : 650ms
    serialize and deserialize items, with empty skipFields
     : 628ms
    serialize and deserialize items, skip field "b"
     : 491ms
    serialize and deserialize items, skip non-existing field "a"
     : 644ms
    serialize and deserialize items, skip field "6"
     : 633ms

    serialize and deserialize items, without skipFields
     : 608ms
    serialize and deserialize items, with empty skipFields
     : 657ms
    serialize and deserialize items, skip field "b"
     : 475ms
    serialize and deserialize items, skip non-existing field "a"
     : 650ms
    serialize and deserialize items, skip field "6"
     : 655ms

    serialize and deserialize items, without skipFields
     : 605ms
    serialize and deserialize items, with empty skipFields
     : 645ms
    serialize and deserialize items, skip field "b"
     : 476ms
    serialize and deserialize items, skip non-existing field "a"
     : 648ms
    serialize and deserialize items, skip field "6"
     : 650ms

large sized items ([~87818 bytes per item](https://github.com/timkuijsten/js-bson/blob/1bc99326a2ae749c35572f4edd936677305a525b/test/node/test_skip_fields.js#L52-L63)):

    ################
    creating 20000 large items...
     : 347ms

    serialize and deserialize items, without skipFields
     : 1855ms
    serialize and deserialize items, with empty skipFields
     : 1171ms
    serialize and deserialize items, skip field "b"
     : 911ms
    serialize and deserialize items, skip non-existing field "a"
     : 1109ms
    serialize and deserialize items, skip field "6"
     : 1117ms

    serialize and deserialize items, without skipFields
     : 1074ms
    serialize and deserialize items, with empty skipFields
     : 1111ms
    serialize and deserialize items, skip field "b"
     : 976ms
    serialize and deserialize items, skip non-existing field "a"
     : 1377ms
    serialize and deserialize items, skip field "6"
     : 1470ms

    serialize and deserialize items, without skipFields
     : 1305ms
    serialize and deserialize items, with empty skipFields
     : 1459ms
    serialize and deserialize items, skip field "b"
     : 1231ms
    serialize and deserialize items, skip non-existing field "a"
     : 1384ms
    serialize and deserialize items, skip field "6"
     : 1401ms

As you can see the current implementation "without skipFields" beats the new parser "with empty skipFields" most of the time except in the first run (which might have something to do with warming up?). Of course as expected the skipFields wins when skipping a large "b" field, but the win is only significant in the medium object test and does not grow linearly with object size. Skip large b with small objects is ~11% faster. Medium 22% faster. Large <10%.

I think the penalty is higher than expected and the gain is lower than what I had expected. What do you think? Maybe I'm running into some V8 deoptimization?

[0] https://github.com/timkuijsten/js-bson/blob/1bc99326a2ae749c35572f4edd936677305a525b/test/node/test_skip_fields.js
[1] https://github.com/timkuijsten/js-bson/blob/1bc99326a2ae749c35572f4edd936677305a525b/lib/bson/parser/deserializerSkipFields.js

**Comment by christkv** [comment]
it's possible that you are hitting de-optimizations, the current version of the parser was very carefully profiled to avoid all that I could find so it could be competitive with the c++ parser.

**Comment by timkuijsten** [comment]
Close because this is not the improvement I've hoped for.
