### ISSUE TITLE
0.4.12 changed the default behavior with new optional `ignoreUndefined` parameter: now it saves `undefined` (as `null`)

### ISSUE THREAD

**Issue by triccardi-systran** [mongodb/js-bson#146]
Between 0.4.11 and 0.4.12 the default behavior changed with new optional `ignoreUndefined` parameter:
* 0.4.11: undefined leafs were not serialized, and just ignored
* 0.4.12: new `ignoreUndefined` flag is false by default, which means undefined leafs are sent to MongoDB server (which saves it as `null`).

npm mongodb 2.0.34 depends on mongodb-core 1.2.0 which depends on bson ~0.4. This means different installation times for mongodb 2.0.34 have different behaviours (it took some time to find the issue...).

Regression introduced by commit c19734d907bcd8e4f32f906b414ea09f55df341c

**Comment by christkv** [comment]
yeah this had to be rolled back as it was causing production issues for customers. you will have to enable that flag to be able to enable the behavior to ignore undefined.

https://jira.mongodb.org/browse/NODE-563

**Comment by triccardi-systran** [comment]
This is a breaking change in behaviour, it should probably not happen in a patch version for `bson`.
The changes in https://jira.mongodb.org/browse/NODE-563 add support for the new parameter from the top level API, so we can manually go back to the old behaviour, but still change the default behaviour from prior 2.0.x versions.

I understand it was different in `node-mongodb-driver` 1.x, and latest 2.0.x versions go back to this because that's what we want, but having undocumented changes in a patch release of `bson` creates more issues than it fixes...

At least bumping the major version of `bson` would keep old 2.0.x `node-mongodb-driver` working as before.
Then if you want to change the default behaviour in a patch release of `node-mongodb-driver` (which is not allowed by semver)  it's still possible, but won't break older versions.

**Comment by christkv** [comment]
This was rolling back the initial mistake. the change in behavior on 0.4.11 should have been under a flag in the first place meaning you have to explicitly set it to change the default behavior in 1.4.x and 2.0.x.

**Comment by triccardi-systran** [comment]
Ah OK, it's a recent regression (`bson` 0.4.9), I thought it was always there since `node-mongodb-driver` 2.0.0, my bad...
Now it's fixed since `bson` 0.4.12.
(Maybe it could have been identified as a regression fix in the commit in 0.4.12 though)

Thank you!
