### ISSUE TITLE
the file map.js has an error of llegal return statement

### ISSUE THREAD

**Issue by wusuopu** [mongodb/js-bson#148]
The error message is:
```
/Users/lcj/Projet/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Error transforming /Users/lcj/Projet/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/map.js to JS: Error: Parse Error: Line 7: Illegal return statement
```

My library version is:
  * node: 0.12.7
  * mongodb: 2.0.45
  * bson: 0.4.15

It can work before.
I want to install the older version, but I find the version 0.4.11 is not exist.

**Comment by christkv** [comment]
you are right, I have published a 0.4.16 with the fix to NPM.

0.4.11 had to be pulled due to it causing a critical regression that could cause serious problems. unfortunately when you pull a release on NPM there is no way to replace it so it's gone.
