### ISSUE TITLE
Node 4+ Build Problems

### ISSUE THREAD

**Issue by pr1ntr** [mongodb/js-bson#150]
Hi,
I get this error:
`{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }` 
 with Node 4.2 on 0.2.x and 0.4.x

**Comment by christkv** [comment]
If you upgraded your node version you need to rebuild all your native code modules. Also only the 0.4.x branch supports 4.x as it does not include the c++ extension anymore.
