### ISSUE TITLE
Instance of Error for invalid ObjectId values in constructor

### ISSUE THREAD

**Issue by hhromic** [mongodb/js-bson#156]
Hello,
I realised that when constructing a new `ObjectId` object, you validate the passed `id` value (if it can be converted to an hex string). This is just fine, however you throw a generic `Error` object ([here](https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L38), [here](https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L224) and [here](https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L219)) when the validation fails. This makes tracking the error unconvenient. From official [Joyent's design patterns for errors](https://www.joyent.com/developers/node/design/errors), it is suggested this:

`3. Use the Error's name property to distinguish errors programmatically.
When you need to figure out what kind of error this is, use the name property. Built-in JavaScript names you may want to reuse include "RangeError" (an argument is outside of its valid range) and "TypeError" (an argument has the wrong type). For HTTP errors, it's common to use the RFC-given status text to name the error, like "BadRequestError" or "ServiceUnavailableError".`

As you can see, you could use the `TypeError` class instead of the generic `Error` object. Because TypeError is a subclass of Error, all existing code will continue to work flawlessly and new code can more easily track an invalid argument error. An alternative would be to create your own Error subclass but I don't think this is necessary as TypeError covers the kind of error nicely.

What do you think?

Thanks!
Hugo.

**Comment by christkv** [comment]
sounds fine, send me a PR so you get your commit in :) :+1:

**Comment by hhromic** [comment]
hello!
any updates about getting this improvement merged in for an upcoming version? Thanks!
Hugo.

**Comment by christkv** [comment]
It will be merged in the next 4.3 release as it's considered a potentially breaking behavior. for the 4.2.x branch it will stay as is.

**Comment by hhromic** [comment]
Oh I see, looking fwd for the next major version then!
thanks!

**Comment by christkv** [comment]
there are new types being discussed for the next mongodb version so depending on what comes of that it might be 5.0.x

**Comment by christkv** [comment]
I'm going to close this for now as I'm not planning any modifications to the types in the next couple of months.
