### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by fresheneesz** [mongodb/js-bson#162]
The only thing on the readme is `serialize` and `deserialize`. It doesn't even tell you how to install this via npm (I'm pretty sure its not `npm install js-bson`). Looks like there are at least 20 undocumented submodules available. This is an unacceptably poor amount of documentation. Please spend some time creating documentation so people can use your module.

**Comment by fresheneesz** [comment]
I see there are meticulous annotations in the source code. Are those used to generate documentation? If so, a link should be put in the readme.

**Comment by fresheneesz** [comment]
https://github.com/mongodb/js-bson/pull/163

**Comment by williamkapke** [comment]
@fresheneesz if all you need is ObjectID, you can use [bson-objectid](https://www.npmjs.com/package/bson-objectid) - it has docs and is 100% compatible. ;)

**Comment by fresheneesz** [comment]
@williamkapke Thanks, good to know. I still think this project needs better docs, tho.

**Comment by christkv** [comment]
updated after bson refactoring and added link to the driver docs that contains the api information for all the bson types.
