### ISSUE TITLE
Release/obj.target/bson/ext/bson.o] Error 1

### ISSUE THREAD

**Issue by mictadlo** [mongodb/js-bson#165]
I tried to install "mongodb": "~2.1.5", but recieved the below error. I am using *mongodb 3.2.1*

    ../ext/bson.cc: In static member function ‘static v8::Handle<v8::Value> BSON::BSONDeserializeStream(const int&)’:
    ../ext/bson.cc:1011:1: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
    make[1]: *** [Release/obj.target/bson/ext/bson.o] Error 1
    make[1]: Leaving directory `/home/lorencm/Downloads/mongo-invoices/node_modules/mongodb/node_modules/bson/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:100:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.2.0-23-generic
    gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
    gyp ERR! cwd /home/lorencm/Downloads/mongo-invoices/node_modules/mongodb/node_modules/bson
    gyp ERR! node -v v5.5.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    make: *** [node_gyp] Error 1
    child process exited with code 2

**Comment by christkv** [comment]
you probably have old and new version of drivers side by side. delete your node_modules directory and any npm cache you have.
