### ISSUE TITLE
bson's injex.js was not pointing to the ideal directory

### ISSUE THREAD

**Issue by jennylia** [mongodb/js-bson#167]
/node_modules/mongodb/node_modules/bson/ext/index.js
line 10

I don't really understand how this file got here for mongod as I don't see the ext direcotry in this git tree, but in line 10, there was a line: 	  bson = require('../build/Release/bson');  
This above statement caused errors in the console:

> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

I changed the above line to: bson = require('../browser_build/bson') according to stackoverflow. Should this be updated somehow?

Cheers,

**Comment by christkv** [comment]
you have a mixed up set of versions. if you are using 2.1.x or 2.0.x of the driver you should never even have the ext which is the legacy c++ version of the parser and not supported anymore. I suggest blowing away your npm cache and node_modules directory.
