### ISSUE TITLE
Failed to load bson c++ extension, using pure js version - Centos Meteor Mongodb

### ISSUE THREAD

**Issue by sreejith12** [mongodb/js-bson#168]
I am trying to deploy the meteor app in server as production mode. I have node(0.10.41), mongodb(v2.6.11) and npm(3.7.3) in my centos 6 server. while running node main.js, I am getting below errors :

'Failed to load bson c++ extension, using pure js version , 
.../cfs_gridfs/npm/node_module/bson/build/release/bson.node invalid ELF header'.

**Comment by digz6666** [comment]
I'm using node 0.10.43 and getting same error.

```
app/programs/server/npm/node_modules/mete
or/cfs_gridfs/node_modules/mongodb/node_modules/bson/build/Release/bson.node: in
valid ELF header
```

**Comment by christkv** [comment]
upgrade to the latest driver and you will not get these errors

**Comment by freakk101** [comment]
When you install the mongoose module by npm, it does not have a built bson module in it's folder. In the file node_modules/mongoose/node_modules/mongodb/node_modules/bson/ext/index.js, change the line

bson = require('../build/Release/bson');
to

bson = require('bson');
