### ISSUE TITLE
Version 0.4.11 unpublished from npm

### ISSUE THREAD

**Issue by alexcrist** [mongodb/js-bson#176]
It appears that 0.4.11 has been unpublished from npm.

Visiting https://registry.npmjs.org/bson/-/bson-0.4.11.tgz returns 
> {"error":"package could not be found."}

Both the sandwiching versions 0.4.10 and 0.4.12 seem to be fine.

**Comment by programmerdave** [comment]
Duplicate: https://github.com/mongodb/js-bson/issues/147

**Comment by alexcrist** [comment]
Ah, right you are, thanks @programmerdave. Will close this issue.
