### ISSUE TITLE
Use of parseInt where Math.floor would be appropriate

### ISSUE THREAD

**Issue by zbjornson** [mongodb/js-bson#179]
Throughout objectid.js (e.g. https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L15) `parseInt` is used to, I think, provide the same functionality as `Math.floor`. In all cases, the argument is already a number and not a string, so `Math.floor` would be appropriate and [faster](http://arnorhs.com/2012/05/30/comparing-the-performance-of-math-floor-parseint-and-a-bitwise-shift/). Would a PR be accepted to change this over?

**Comment by christkv** [comment]
before I change anything please provide a benchmark showing if there is actual speedup

**Comment by zbjornson** [comment]
You just fixed this in aa0b545. :) (Although the browser_build is out of date now and still contains the inappropriate uses of `parseInt`.)

**Comment by christkv** [comment]
I'm not even looking at that I'll consider a PR for a proper browser build but it would need to polyfill Buffer from node.js to work properly

**Comment by zbjornson** [comment]
Say again? You yourself fixed this issue in a commit 6 hrs ago.

**Comment by christkv** [comment]
I had time to do a quick performance review and saw ~~ worked even better
