### ISSUE TITLE
npm install requires 4GB of RAM

### ISSUE THREAD

**Issue by bitliner** [mongodb/js-bson#180]
When I install a package depending from mongoose, it installs also bson.

But when it compiles bson, it asks for 4GB of RAM.

**Comment by christkv** [comment]
Not sure why if you are using the latest mongoose it should not be compiling anything. You should probably open a ticket on the mongoose site however as it might be dependencies mongoose itself relies on.

**Comment by bitliner** [comment]
I will check it out, some changes caused this increasing of RAM to 4GB, before it was requiring less RAM.

But still is it normal using 4 GB to compile bson? (that is why my question is here)

**Comment by christkv** [comment]
if you are using a a mongoose version that has the newest 2.1.x driver it should not compile anything. However 4Gb for compile might be node.js thing.
