### ISSUE TITLE
serializeWithBufferAndIndex returns wrong offset

### ISSUE THREAD

**Issue by gordonmleigh** [mongodb/js-bson#181]
I don't think that it should be subtracting 1 from the position on the return statement - the docs says it returns the next write index in the buffer, but this gives the position 1 before the next position to write to in the buffer.

The only problem is, this is a breaking change if you fix it.

**Comment by christkv** [comment]
Can you restate the issue as I'm not clear on what it is you are talking about

**Comment by gordonmleigh** [comment]
Sorry.  I got it wrong anyway actually.  Here is the problem -

The function [`serializeWithBufferAndIndex()`](https://github.com/mongodb/js-bson/blob/master/lib/bson/bson.js#L67) is supposed to return the new offset to write to in the buffer, according to the `@return` line in the description.  

The variable `serializationIndex` actually holds this value after the call to `serialize()` (it returns the buffer index, not the size as seems to be assumed) but then `serializeWithBufferAndIndex()` adds the `startIndex` and subtracts 1 to give a seemingly useless value as the return.

Unless I've got the wrong idea about what is supposed to be returned, I don't think this is correct.

**Comment by christkv** [comment]
Can you provide a failing test case or example code as I'm still not one hundred percent sure what your usecase is

**Comment by gordonmleigh** [comment]
Based on my reading of the comments for `serializeWithBufferAndIndex()` the following code should write the records one after another:

```js
const BSON = new bson.BSONPure.BSON();

let offset = 0;

for (let record of records) {
  // serialize
  offset = BSON.serializeWithBufferAndIndex(record, false, buffer, offset);
}
```

Instead, the value of offset after the call is as follows (from [line 72 in master](https://github.com/mongodb/js-bson/blob/master/lib/bson/bson.js#L72))

```js
offset = 2*offset + objectSize - 1;
```

This is because the `serialize()` function called in line 69 returns the final offset into the buffer, to which the `startIndex` is added again in the `serializeWithBufferAndIndex()`.

**Comment by gordonmleigh** [comment]
Thanks for your attention on this.  Can you say why you subtract 1 from the return?  That doesn't match the description in the comment header.

**Comment by christkv** [comment]
It really should not return the next index (could be pointing to undefined) but the last index it wrote too so the method docs are wrong.
