### ISSUE TITLE
path issue for build/Release/bson in npm

### ISSUE THREAD

**Issue by serganus** [mongodb/js-bson#182]
Hi,

I am using some package that uses `bson` whenever i run it pops the error:

`{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }`
`js-bson: Failed to load c++ bson extension, using pure JS version`

I think some issue with the path, can you help me fix it?

**Comment by christkv** [comment]
just a warning npm installs the driver correctly but cannot find the c++ extension. never drivers do not use the c++ bson driver so yo might want to mention that to the package maintainer so he upgrades.
