### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by brandonros** [mongodb/js-bson#184]
Is there a reason there is no C++ native module?

**Comment by christkv** [comment]
Yes. It was abandoned as it only performed about 10% better for the huge additional maintenance pain. Nobody as of yet has shown any compelling evidence that this was a mistake.

**Comment by brandonros** [comment]
@christkv How would you recommend fixing my performance "issues" that collectively point to BSON deserializing being the slowest part of my app?

The query takes 20ms, the deserializing can take up to to 2s of a 100% pegged thread (obviously)...

**Comment by christkv** [comment]
Not sure what it is you are deserializing that would cause 2s of time
