### ISSUE TITLE
Add  webpack support

### ISSUE THREAD

**Issue by n1ru4l** [mongodb/js-bson#185]
When I try to require / import bson this way

```javascript
import bson from 'bson'
//or
const bson = require('bson')
```

I just get a function from which I can not get the BSON object.

**Comment by christkv** [comment]
Sorry I would not know where to start on this. I'm working on a browser-mongodb type framework (db part of meteor) that will have a free standing bson parser for the client. But right now have no time to dig into why webpack won't package up the module correctly. I'll be happy to consider any PRs

**Comment by n1ru4l** [comment]
For people with the same issue:

I switched to https://github.com/sitegui/js-binary, which works fine with webpack.

**Comment by dsvictor94** [comment]
I try use bson with webpack but not work properly.

```javascript
const { BSON } = require('bson');
const bson = new BSON();
const buffer = bson.serialize({teste: "test"}); // return a Buffer, that is a Node stuff 
console.log(buffer);
const array = new Uint8Array(buffer); // cast to Uint8Array 
console.log(array);
console.log(bson.deserialize(array)); //return a wrong result and some times, `buffer.copy undefined`
// Object {20,0,0,0,2,116,101,115,116,0,5,0,0,0,116,101,115,116,0,0: "20,0,0,0,2,116,101,115,116,0,5,0,0,0,116,101,115,116,0,0"}
const bufferContructor = bson.serialize({}).constructor; // if get the Buffer constructor
console.log(bson.deserialize(bufferContructor(array))); //and pass a Buffer works
```
I don't know why when a use `browser_build/bson.js` it works direct with Uint8Array but with webpack it not.
