### ISSUE TITLE
ObjectID.equals not transitive across `bson` module versions

### ISSUE THREAD

**Issue by suprememoocow** [mongodb/js-bson#187]
We have a large mongodb application, which also uses `mongoose` and several other modules which ship with different versions of `mongodb` (and therefore different versions of `bson`)

Unfortunately, we've found that `ObjectID.equals` is not transitive across versions of `bson`. 

It's fairly easy to recreate this issue with a small project. For example:

```sh
npm i bson@0.4.23 --save
npm i mongodb@2.2.0 --save

npm ls
mongo-objectids-equals-bug@1.0.0 /Users/andrewn/code/test/mongo-objectids-equals-bug
├── bson@0.4.23
└─┬ mongodb@2.2.0
  ├── es6-promise@3.0.2
  ├─┬ mongodb-core@2.0.3
  │ ├── bson@0.5.1
  │ └─┬ require_optional@1.0.0
  │   ├── resolve-from@2.0.0
  │   └── semver@5.2.0
  └─┬ readable-stream@1.0.31
    ├── core-util-is@1.0.2
    ├── inherits@2.0.1
    ├── isarray@0.0.1
    └── string_decoder@0.10.31
```

Here is an example of how the failure shows up:

```js
var BaseObjectID = require('mongodb').ObjectID;
var BSONObjectID = require('bson').ObjectID;
var assert = require('assert');

var o1 = new BaseObjectID();
var o2 = new BSONObjectID(o1.toHexString())

assert.strictEqual(o1.toHexString(), o2.toHexString());
assert.strictEqual(o1.equals(o2), true); // bson@0.5.1 `equals` works
assert.strictEqual(o2.equals(o1), true); // bson@0.4.23 `equals` fails (!!)
```

Obviously this example is fairly contrived, but in the real world, it's pretty difficult to ensure that the same version of `bson` is installed with all modules in a big project. Eg, still using `mongoose@4.4.x` which uses `bson@0.4.23` but `mongodb@2.2.0` ships with `bson@0.5.0`.

The problem appears to be that `bson@0.4.x` always assumes that `ObjectID.id` is a string, while in `bson@0.5.x` `ObjectID.id` can also be a buffer.

**Comment by christkv** [comment]
I'm not sure if there is any simple answer to this beside either adding the ability of 0.5.x to handle string based objectids or you writing a custom compare version. I'm open to suggestions
