### ISSUE TITLE
utf8 character support

### ISSUE THREAD

**Issue by agalazis** [mongodb/js-bson#188]
when I encode and decode special utf8 characters I get ` <?>` symbols if there is any configuration I can do, this should be reflected in the documentation otherwise are there any support plans?

**Comment by agalazis** [comment]
ping... I guess this relates to https://github.com/mongodb/js-bson/issues/42 which was closed without a valid solution.

**Comment by kozi** [comment]
Does this mean there is no support for UTF-8?

**Comment by smonkey72** [comment]
Demo fiddle: https://jsfiddle.net/ked3vgtn/

**Comment by agalazis** [comment]
I think in my case the difference is that it wasn't encoded and decoded
using the browser version. On the server I was using the node version to
serialize and then the browser received it(using websockets) and
deserialized it . I can clearly see in the repo that the browser_build is 2
year old but the lib 4 months, so I guess they are not the same?

*Andreas Galazis*
Front End Developer

*StarLeaf:*  2748
*Email:*  andreas.galazis@heg.com
*Office:*  West Street, GU21 6EB Woking


123-Reg Limited
The Old Vinyl Factory
252 Blyth Road
Hayes
UB1 1HA
United Kingdom

**Comment by christkv** [comment]
they are out of sync, I suggest using web-pack to build your own version for use in the browser. 0.5.6 fixes some issues that should make it easier to use or build your own release.
