### ISSUE TITLE
parsing objects with uninstantiated bsontypes

### ISSUE THREAD

**Issue by timkuijsten** [mongodb/js-bson#192]
The serializer expects that objects are instantiations of what they claim to be. This leads to trouble when trying to execute functions on those acclaimed types.

$ cat test.js

    var bson = require('bson');
    var BSON = new bson.BSONPure.BSON();

    console.log(BSON.serialize({ foo: { _bsontype: 'ObjectID', id: { copy: true } } }))

$ node test.js

    node_modules/bson/lib/bson/parser/serializer.js:253
        value.id.copy(buffer, index, 0, 12);
                 ^

    TypeError: value.id.copy is not a function
        at serializeObjectId (node_modules/bson/lib/bson/parser/serializer.js:253:14)

The same happens with Timestamps (and Longs) and a quickscan reveiled several other types like serializeDecimal128.

I came across this after trying to serialize an item with a Timestamp[1], that has been stored in IndexedDB (that uses structured clone and thus saves Timestamp as a regular object). I've created a quick workaround[2] but I'm not sure if this is the right way forward.

[1]  `BSON.serialize({ foo: { _bsontype: 'Timestamp', low_: 2, high_: 1471694771 } })`
[2] https://github.com/timkuijsten/js-bson/commit/508bb337e110d8ee7197b01584b217523709b317

**Comment by christkv** [comment]
the bson serializer expects it's types to be honored so you will have to write pre-serializer if you wish to move docs between systems in this fashion or stick to plain json types. no plans to allow for any hybrid like type objects.
