### ISSUE TITLE
TypeError: __webpack_require__(...).native is not a function

### ISSUE THREAD

**Issue by clitetailor** [mongodb/js-bson#197]
![image](https://cloud.githubusercontent.com/assets/16368559/19685223/b35fe53a-9ae5-11e6-9f2e-c23b5b1461ec.png)
Sorry, my english is not good. I got this problem when i work with webpack and angular 2. I have no ideal how to solve this.
Can someone help me! Thanks

**Comment by christkv** [comment]
the latest and greatest version should fix this as it's refactored to no longer have these kind of issues
