### ISSUE TITLE
ObjectId.prototype.equals does not work with uppercase hex strings

### ISSUE THREAD

**Issue by nlindley** [mongodb/js-bson#199]
Here is a sample case that I would expect to be `true`.

```js
var a = 'AAAAAAAAAAAAAAAAAAAAAAAA';
var b = new ObjectId(a);
var c = b.equals(a); // => false
```

However, making the string in variable `a` lowercase works.

```js
var a = 'aaaaaaaaaaaaaaaaaaaaaaaa';
var b = new ObjectId(a);
var c = b.equals(a); // => true
```

This appears to be a regression from the following commit.

https://github.com/mongodb/js-bson/commit/aa0b54597a0af28cce3530d2144af708e4b66bf0

If desired, I can prepare a PR for this. I can imagine either converting the string to lowercase before doing the comparison or converting the string to an ObjectId first, so guidance on which approach is preferred would be appreciated.

**Comment by christkv** [comment]
Will be out in 1.0.0 but that does have some breaking changes in the API
