### ISSUE TITLE
improve fromHex and toHex

### ISSUE THREAD

**Issue by caub** [mongodb/js-bson#201]
Why isn't toHex just `.toString('hex')`

and fromHex: `new ObjectId(Buffer.from(string24hexChars, 'hex'))`

**Comment by christkv** [comment]
because it did not use to be a buffer and toString('hex') did not even exist when this code was first written. However I'm going to make it use toString from the buffer if the id is a Buffer instance.

new ObjectId(Buffer.from(string24hexChars, 'hex')) works as far as I know.

**Comment by caub** [comment]
I use more `createFromHexString(string24hexChars)`
