### ISSUE TITLE
util.inspect(objectId) fails on 1.0.2

### ISSUE THREAD

**Issue by MarkusMattinen** [mongodb/js-bson#203]
Simple test case that works with 1.0.1, but fails with 1.0.2:
```
var bson = require('bson');
util.inspect(new bson.ObjectID());
```

Seems to be caused by: https://github.com/mongodb/js-bson/commit/35f5264446fb74e475ecf25f94ce7b177b5b35fd
ObjectID.prototype.inspect is an alias of ObjectID.prototype.toString, which since that commit passes its first parameter to Buffer.toString.
However, util.inspect calls ObjectID.prototype.inspect with two parameters: depth (an integer or null, default 2) and options (an object).
This causes an error with a stack trace like:

```
> util.inspect(new bson.ObjectID())
TypeError: Unknown encoding: 2
    at Buffer.slowToString (buffer.js:479:17)
    at Buffer.toString (buffer.js:492:27)
    at ObjectID.toString (node_modules/bson/lib/bson/objectid.js:174:20)
    at formatValue (util.js:352:36) 
    at Object.inspect (util.js:186:10)
```

**Comment by MarkusMattinen** [comment]
Just noticed the discussion here: https://github.com/mongodb/js-bson/commit/35f5264446fb74e475ecf25f94ce7b177b5b35fd
I'm also using Node.js 6.9.1.

**Comment by MarkusMattinen** [comment]
Updating to Node.js 6.9.2 does not resolve the issue for me.

**Comment by deser** [comment]
Occurs on windows 10

**Comment by christkv** [comment]
hot fix out in driver 2.2.18

**Comment by MarkusMattinen** [comment]
Working in 1.0.3 again. Thanks @christkv for the very quick fix!

**Comment by deser** [comment]
Thanks, it's working
