### ISSUE TITLE
BSON.serialize doesn't support buffers bigger than 17MB

### ISSUE THREAD

**Issue by jehowell** [mongodb/js-bson#207]
Please add support for passing in your own buffer to BSON.serialize. 

Options.buffer should be used.

**Comment by jehowell** [comment]
Looked at serializeWithBufferAndIndex, but it still uses the 17MB temp buffer.

**Comment by w9** [comment]
I forked this repo and changed the `MAXSIZE` in `./js-bson/lib/bson/bson.js` to 2147483647 (the maximum allowed by NodeJS).

https://www.npmjs.com/package/w9-bson

**Comment by mbroadst** [comment]
@jehowell @w9 contributions are always welcome. Please provide a PR with your suggested approach, and we can discuss there!

**Comment by w9** [comment]
@mbroadst I'm hesitating on whether to provide this in the form of a pull request. After all, this repo is supposed to be less of a generic BSON library but rather part of the core of Mongodb, and in since Mongodb a document cannot be larger than 17MB, the current restriction makes sense.

Maybe we should create a separate repo for just the exact implementation of BSON protocol as documented in the [official website](http://bsonspec.org/).

**Comment by xaviergonz** [comment]
why not add it as an option instead of a constant then? that way the default mongodb uses is kept as 17mb, yet can be overriden if needed.

**Comment by mbroadst** [comment]
@w9 actually this repo _is_ meant to be the reference implementation of the bson spec, it just also happens to be used as the code implementation for the driver. To that end, I think we should accommodate changes like this.

@xaviergonz that seems like a very reasonable solution. We're going to be releasing an updated version of the repo relatively soon including some changes discovered while updating the corpus tests, if one of you wants to make this PR it would be very welcome.

Thanks!

**Comment by xaviergonz** [comment]
@mbroadst something like this?
https://github.com/mongodb/js-bson/pull/232

**Comment by jancurn** [comment]
Guys, please, can you merge the above PR and allow the custom max size in any other way? We really need this feature, and we'd prefer to avoid working with a forked version.

**Comment by jancurn** [comment]
Just figured out there's a workaround - if you replace the `bson` package with `bson-ext@2.0.0`, then you can use the `maxBSONSize` option when initializing the `BSON` object - see https://github.com/mongodb-js/bson-ext/blob/2.0.0/src/bson.cc#L1283

**Comment by jancurn** [comment]
False alarm, `bson-ext` is also using a hard-coded `MAX_BSON_SIZE` constant - see https://github.com/mongodb-js/bson-ext/blob/2.0.0/src/bson.h#L258

**Comment by jancurn** [comment]
won't be fixed?

**Comment by mbroadst** [comment]
@jancurn this has been fixed for about a year: https://github.com/mongodb/js-bson/blob/master/lib/bson.js#L42

**Comment by jancurn** [comment]
Oh wow, awesome, thanks guys!
