### ISSUE TITLE
bson deserialization issue when receiving data via websocket

### ISSUE THREAD

**Issue by jaritheman** [mongodb/js-bson#208]
I think there is an issue in the bson's deserialization. I can do the following in my JS code without problems:

```
var doc = { 'foo': 'bar' };
var data = this.bson.serialize(doc);
var doc_2 = this.bson.deserialize(data);
console.log(doc_2); //prints Object {foo: "bar"} to console
```

However when the exactly same { 'foo': 'bar' } is received via a websocket, somethign weird happens:

```
onMessage = (event): void => {
	var myUint = new Uint8Array(event.data);            
	var data = this.bson.deserialize(myUint);
	console.log(data); //prints Object {18,0,0,0,2,102,111,111,0,4,0,0,0,98,97,114,0,0: "18,0,0,0,2,102,111,111,0,4,0,0,0,98,97,114,0,0"} to console
}
```

WebSocket's binaryType is set to 'arraybuffer'.

I think this has to do with how the protorype of "data" in the first example is Uint8Array, but in the later case the prototype of "myUint" is TypedArray. And because of that, the internal deserialization of bson messes up. 

I tried this solution http://stackoverflow.com/questions/29707535/sending-bson-from-python-to-javascript-over-websockets, but the result was the same when the data was received via a websocket.

I am using bson 1.0.4.

**Comment by matthiasbayer** [comment]
I had the same problem. I use webpack, so instead of deserializing a Uint8Array I used a Buffer instance, which worked fine.

`
bson.deserialize(Buffer.from(binarydata));
`

**Comment by bumxu** [comment]
BSON `.deserialize()` needs a Node Buffer compatible structure, that browsers ArrayBuffer is not.
In my case https://github.com/feross/buffer with the above Matthias code was the solution.
