### ISSUE TITLE
Feature Request: Custom object to deserialize data to

### ISSUE THREAD

**Issue by rahbari** [mongodb/js-bson#211]
For now adding method from an ES6 class to a deserialized object can be done using Object.assign() or Object.setPrototypeOf() which both have poor performance. It's nice if we can create the object from class (or even the class itself), pass it to BSON deserialize, and data is added to this object (or object instantiated from class) instead of `var object = isArray ? [] : {};` at the first level of deserializing. 

The PDO of PHP provide such functionally:

> PDO::FETCH_CLASS: returns a new instance of the requested class, mapping the columns of the result set to named properties in the class, and calling the constructor afterwards, unless PDO::FETCH_PROPS_LATE is also given.

The API must become available in Core Driver as well.

**Comment by mbroadst** [comment]
@rahbari perhaps you can follow up with some code examples of your desired experience, I think it would greatly assist discussion.

**Comment by rahbari** [comment]
@mbroadst if we want add some functions to a fetched mongodb object we have 4 options:

1. Create the object from class and add the fields to it using `Object.assign(this, fetchedObj)` in the constructor.
2. Use Object.setPrototypeOf(fetchedObj, desiredPrototype) which breaks every optimization in javascript compiler:
> Changing the [[Prototype]] of an object is, by the nature of how modern JavaScript engines optimize property accesses, a very slow operation, in every browser and JavaScript engine.
3. Add the functions to the fetched object using `Object.assign(fetchedObj, desiredPrototype)`
4. Add the fields directly to the desired object which is the fastest but BSON parser and MongodbCoreDriver must provide.

I made a simple benchmark test for the four solution https://jsperf.com/assign-setprototypeof-direct. You can see how faster the fourth approach is with just 5 simple fields.

For now deserialize method use this line to create an empty object to populate data to:
`var object = isArray ? [] : {};`

It's nice the query object get an object with some functions and add the fetched data to it instead of empty object. 

Or when there are multiple documents it can accept a Class, instantiate it and data to this instantiated object instead of and empty object.

**Comment by mbroadst** [comment]
I am quite familiar with how slow changing prototypes can be on objects, and you still have not provided an example of what exactly you want here (even with a benchmark provided). It _sounds_ like what you want is to be able to override [this code](https://github.com/mongodb/js-bson/blob/1.0-branch/lib/bson/parser/deserializer.js#L69) such that you could pass your own object in:

```
const Long = BSON.Long;
let bson = new BSON();
const doc = { long: Long.fromNumber(100) }
const serialized = bson.serialize(doc);

let obj = {
  existingProperty: function() { return 'foo'; }
};

bson.deserialize(data, obj);  // this would also return `obj` for posterity
assert.deepEqual(obj, {
  long: Long.fromNumber(100),
  existingProperty: function() { return 'foo'; }
});
```

Is that what you're asking for?

**Comment by rahbari** [comment]
This is what I'm suggesting from Core Driver perspective:
```
var Server = require('mongodb-core').Server
  , ReadPreference = require('mongodb-core').ReadPreference
  , assert = require('assert');

class Sample {
    foo() {}
    bar() {}
}

var server = new Server({host: 'localhost', port: 27017});

server.on('connect', function(server) {
  // Execute the write
  var cursor = _server.cursor('collection.sample', {
      find: 'collection.sample'
    , query: {}
    , target: Sample  //** Desired class is passed to the cursor object
  }, {
    readPreference: new ReadPreference('secondary');
  });

  // Get the first document
  cursor.next(function(err, sample) {
    //** sample is an instance of Sample
    sample.foo(); 
    sample.bar(); 
  });
});
```

// Start connecting
server.connect();

**Simplest form that this can be achieved (I didn't test it, just as a sample):**

mongodb-core\lib\connection\commands.js:479
```
  var target= typeof options.target == 'function'
    ? new options.target()
    : null;
  var bsonSize, _options;

  // Set up the options
  _options = {
    promoteLongs: promoteLongs,
    promoteValues: promoteValues,
    promoteBuffers: promoteBuffers,
    target: target
  };
```
bson\lib\bson\parser\deserializer.js:36
`return deserializeObject(buffer, index, options, isArray, options.target);`

bson\lib\bson\parser\deserializer.js:39
`var deserializeObject = function(buffer, index, options, isArray, target) {`

bson\lib\bson\parser\deserializer.js:69
`var object = target || (isArray ? [] : {});`

**Comment by mbroadst** [comment]
@rahbari sounds interesting, I think this would be much easier to get into the codebase if you could provide a PR with tests. How does that sound?

**Comment by rahbari** [comment]
@mbroadst I'm interested, So I think I must provide two PR, one for this repo and one for Core. I will try this ASAP.

**Comment by j** [comment]
@rahbari any more info on this?  I'd love this.  Be a great use case for projects like [type-graphql](https://github.com/19majkel94/type-graphql)

**Comment by j** [comment]
@rahbari @mbroadst I too was looking into implementing this.  So one thing I noticed is the data passed into serialize/deserialize from the driver isn't simply the document object.  It looks like it can be any data.  Which brings me to the question: How can I know exactly which items passed to BSON serialization methods are actually documents?

**Comment by j** [comment]
@rahbari https://github.com/mongodb/node-mongodb-native/pull/1698 if you're interested in something like this.

**Comment by rahbari** [comment]
@j I just made a pull request for this feature: https://github.com/mongodb/js-bson/pull/253
Please participate if you're interested in this feature.

**Comment by agolin95** [comment]
Tracked in Jira: https://jira.mongodb.org/browse/NODE-3012

**Comment by j** [comment]
@bajanam why?

**Comment by bajanam** [comment]
@j Thanks for the reply.  This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket. Thanks!
