### ISSUE TITLE
Uncaught TypeError: buffer.readDoubleLE is not a function

### ISSUE THREAD

**Issue by ryanouyang** [mongodb/js-bson#214]
![image](https://user-images.githubusercontent.com/360426/29639060-01c13370-888c-11e7-83cb-9bee1d5a4813.png)

**Comment by ryanouyang** [comment]
bson.js version 1.0.4

**Comment by mbroadst** [comment]
@ryanouyang are you sure you're using the browser build of js-bson? It appears you're missing polyfills for node's buffer.

**Comment by ryanouyang** [comment]
@mbroadst yes, i'm sure. i build it by `npm run build`, and use the `bson.js` file in `./browser_build/` folder.

![image](https://user-images.githubusercontent.com/360426/29672182-18bbc40e-891e-11e7-837e-31fac886feee.png)

[bson.js](https://github.com/mongodb/js-bson/files/1249275/bson.txt)

**Comment by mbroadst** [comment]
@ryanouyang you're right this looks like a bug where `deserialize` isn't checking if a `Buffer` or `UInt8Array` is being passed in.  Even though the browser build includes a polyfill for node's Buffer, it needs to wrap the incoming `UInt8Array` with that buffer if its not already a `Buffer`.

**Comment by christkv** [comment]
js-bson never supported UInt8Array as it was optimized for speed and had to support node versions where node buffers are not compatible with UInt8Array. In fact the README says it has to be a Node style buffer. See the work around mentioned in this ticket https://github.com/mongodb/js-bson/issues/208 for how to get it to work with UInt8Array
