### ISSUE TITLE
new (require('bson'))()  vs    new require('bson')()

### ISSUE THREAD

**Issue by robertlight** [mongodb/js-bson#216]
What is the difference between the two following lines of code:

var BSON_1 = new (require('bson'))();
var BSON_2 = new require('bson')();

BSON_1.calculateObjectSize({})    works fine.
BSON_2.calculateObjectSize({})   gets me a 
                                  TypeError: Cannot read property 'calculateObjectSize' of undefined

???

**Comment by Loksly** [comment]
It is caused by operator preference. Not related to mongodb-jsbson library,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
Check this code:

	var assert = require('assert');
	var bson = require('bson');

	var BSON_1 = new (require('bson'))();
	var BSON_2 = new require('bson')();
	var BSON_3 = (new require('bson'))();
	var BSON_4 = new bson(); // <--- easier way to read

	console.log(typeof BSON_1, typeof BSON_2, typeof BSON_3, typeof BSON_4);
	//outputs: object undefined undefined object

	assert(BSON_1);
	assert(!BSON_2);
	assert(!BSON_3);
	assert(BSON_4);

	BSON_1.calculateObjectSize({});
	BSON_2.calculateObjectSize({}); //fails as it is undefined
	BSON_3.calculateObjectSize({}); //fails as it is undefined
	BSON_4.calculateObjectSize({}); //works flawlessly

**Comment by mbroadst** [comment]
@robertlight please see the above comment for your answer

@Loksly thanks a lot!
