### ISSUE TITLE
serializeWithBufferAndIndex doesn't work

### ISSUE THREAD

**Issue by gitawego** [mongodb/js-bson#220]
with follow example,  bson writes 3 times first item (data[0]) into the buffer, instead of writing 3 documents (data[0],data[1],data[2]).

it works well with ``serialize``

```js
const BSON = require('bson');
const MAXSIZE = 1024 * 1024 * 17;

const fs = require('fs');
const bson = new BSON();
const file = './test.bson';
let bf = new Buffer(MAXSIZE);
const data = [{
	a:1,
	b:new Date('2019-01-01')
},{
	a:2,
	b:new Date('2019-01-02')
},{
	a:3,
	b:new Date('2019-01-03')
}];
let idx =0;
const chunks = [];
data.forEach((item,i)=>{
	console.log(item,i);
	//const doc = Buffer.from(bson.serialize(item));
	//chunks.push(doc);
	idx = bson.serializeWithBufferAndIndex(item,bf,{
		index:idx
	})+1;
});
//bf = Buffer.concat(chunks);
console.log(bf.length);
fs.writeFileSync(file,bf.slice(0,idx));
```

**Comment by kmahar** [comment]
Thanks for bringing this to our attention! We've identified the source of the bug - please see #221 for details.
This fix will appear in version 2.0.0 of js-bson, which will be released concurrently with the Node driver release for MongoDB version 3.6.
