### ISSUE TITLE
Type documentation

### ISSUE THREAD

**Issue by tunderdomb** [mongodb/js-bson#236]
It would be helpful to link to the actual docs, or better yet - document the types in the readme. The readme says 

> For all BSON types documentation, please refer to the documentation for the MongoDB Node.js driver.

But it's nearly impossible to find the type docs from there.
If anyone's looking for them, it's here: https://docs.mongodb.com/manual/reference/bson-types/

**Comment by mbroadst** [comment]
@tunderdomb PRs are welcome! It might have taken less time to submit a PR adding this link than to create this issue 😄

**Comment by mbroadst** [comment]
There is also https://bsonspec.org/

**Comment by tunderdomb** [comment]
Just did it! https://github.com/mongodb/js-bson/pull/237 :)
I did it in parallel, and wanted to write an issue in case someone needs the info before the PR is merged and published.

**Comment by mbroadst** [comment]
merged in 4af4741
