### ISSUE TITLE
Using bson with rollup.js

### ISSUE THREAD

**Issue by palkafilip** [mongodb/js-bson#238]
Hi guys,

Im working with project that is written in Node CommonJS modules. My point was to make this project accessible from a browser. I decided to use Rollup.js, so when the bundle is created you can include script in browser and use functions from library (thanks to iife format). I needed to install plugins for Rollup to convert CommonJS modules into ES6 modules, so browser can understand it.

Everything is fine, except that this project uses bson library. This bson library is required in one of my modules which uses some of it's functions. After I create a bundle and include it into index.html an error appears in console which says: 

> "require is not defined."

When I look inside the created bundle there are some requires.

```
var Map = require('./map'),
  Long = require('./long'),
  Double = require('./double'),
  Timestamp = require('./timestamp'),
  ObjectID = require('./objectid'),
  BSONRegExp = require('./regexp'),
  Symbol$1 = require('./symbol'),
  Int32 = require('./int_32'),
  Code = require('./code'),
  Decimal128 = require('./decimal128'),
  MinKey = require('./min_key'),
  MaxKey = require('./max_key'),
  DBRef = require('./db_ref'),
  Binary = require('./binary');
```

I have created simple code in Plunker to illustrate you my config and simplified structure. https://plnkr.co/edit/YuiVJxhwhjUQ0Flw0Mg3?p=preview

In this plunker there are two simple modules, which one requires bson library, and second requires this first module. There is also Rollup config file, where I use plugins.

I'm really confused. Am I misunderstanding something? Why isn't it converted into ES6 modules just like other of my code?

**Comment by mbroadst** [comment]
@palkafilip are you using the `1.0-branch` or `2.0.0` of this module? We don't have much experience using `js-bson` with rollup, but we do provide a browser build using webpack, so it's definitely possible. I suspect this has more to do with your rollup configuration?

**Comment by palkafilip** [comment]
@mbroadst I'm using 2.0.0. U are right, this is possible. The problem was with my rollup configuration indeed. Thanks for answer.
