### ISSUE TITLE
only one instance of babel-polyfill is allowed?

### ISSUE THREAD

**Issue by jpancake** [mongodb/js-bson#240]
`Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (bundle.js:11563)
    at Object.<anonymous> (bundle.js:11582)
    at __webpack_require__ (bundle.js:3214)
    at Object.<anonymous> (bundle.js:11545)
    at __webpack_require__ (bundle.js:3214)
    at bundle.js:3257
    at bundle.js:3260
    at webpackUniversalModuleDefinition (bundle.js:3192)
    at Object../node_modules/bson/browser_build/bson.js (bundle.js:3194)
    at __webpack_require__ (bundle.js:710)`

Currently using:
BSON 2.04
Webpack 4.1.1
babelv7 beta 40.

Everything works fine using bson v1.04. I only have one call to babel-polyfill in my entry point on my Webpack config.

**Comment by AdmiralPotato** [comment]
Same issue here; My application uses promises all over the place, so it requires `babel-polyfill` be added to the Webpack entry point to solve the error "ReferenceError: regeneratorRuntime is not defined";

Here are my relevant package versions:
```JSON
{
    "babel-core": "6.26.3",
    "babel-polyfill": "6.26.0",
    "bson": "2.0.4",
    "webpack": "3.8.1"
}
```

The trace says that the "Uncaught Error: only one instance of babel-polyfill is allowed" error is coming from the file `node_modules/bson/browser_build/bson.js`.

**Comment by mbroadst** [comment]
@AdmiralPotato if you're already transpiling, there should be no need to use the "browser build" of js-bson, simply use the package directly and transpile the whole project

**Comment by mbroadst** [comment]
In version 4.x of the library we have completely overhauled our browser builds. Please take a look at those, your issues should be resolved.
