### ISSUE TITLE
Should an Int32 type be able to compare equal to itself?

### ISSUE THREAD

**Issue by pzrq** [mongodb/js-bson#241]
## Issue and test
A test case could be something like:

```
$ node
> Int32 = require('bson').Int32
{ [Function: Int32] Int32: [Circular] }
> Int32(35) === Int32(35)
false
# I expected true?

# A possible reason?
> Int32.prototype
Int32 { valueOf: [Function], toJSON: [Function] }
> Int32.prototype.equals
undefined
```

## Environment info

```
pzrq@rocket:~/Projects/charts$ nvm --version
0.33.8
pzrq@rocket:~/Projects/charts$ node --version
v8.9.4
pzrq@rocket:~/Projects/charts$ npm --version
5.8.0
pzrq@rocket:~/Projects/charts$ cat package-lock.json | grep bson
    "bson": {
      "resolved": "https://registry.npmjs.org/bson/-/bson-1.0.4.tgz",
        "bson": "1.0.4",
        "bson": "1.0.4",
        "bson": "github:mongodb/js-bson#78d0c9f2aa77925f9a01a6a2a2ed1d664df948c6"
        "bson": {
          "version": "github:mongodb/js-bson#78d0c9f2aa77925f9a01a6a2a2ed1d664df948c6"
        "bson": "1.0.4",
            "bson": "1.0.4",
```

I tried upgrading the `bson` version as a `v2.0.4` exists, but I suspect based on the [int_32.js](https://github.com/mongodb/js-bson/blob/v2.0.4/lib/bson/int_32.js) that won't actually help.

**Comment by mbroadst** [comment]
@pzrq unfortunately not, because JavaScript. The two instances of `Int32` are different objects, and that's what you're equating with your `===`: the address of the object, rather than the value of the object. You can accomplish this in a few ways:
```
Int32(35).value === Int32(35).value
Int32(35).valueOf() === Int32(35).valueOf()
```

I agree that it seems we should have a consistent API for all these types, as `equals` is only implemented for a few types (Decimal128, Long, ObjectId). I'll make a ticket for this, thanks!

**Comment by pzrq** [comment]
@mbroadst Thanks for the explanation, a future ticket sounds good here.

Lately I've found myself running into `'JS' !== 'Python'` quite a bit, e.g. [`__eq__`](https://docs.python.org/3/reference/datamodel.html#object.__eq__) would be a really nice semantic to have. As you alluded to, that's for the language designers to determine and then let us know how we can write such code 😄
