### ISSUE TITLE
deserializeStream throws `corrupt bson message`

### ISSUE THREAD

**Issue by bewt85** [mongodb/js-bson#244]
Hi,
I was using v2.0.4 of the library for some testing and had an issue reading back data using `deserializeStream`.  It looks like the problem is on [this line](https://github.com/mongodb/js-bson/blob/2.0.0/lib/bson/parser/deserializer.js#L27) specifically the bit which says `buffer.length !== size`.

When you're [deserializing a stream](https://github.com/mongodb/js-bson/blob/2.0.0/lib/bson/bson.js#L196) of objects we'd expect the buffer to be bigger than the current object right?

This change seems to be introduced since the [1.0-branch](https://github.com/mongodb/js-bson/blob/2.0.0/lib/bson/bson.js#L196).

There's also a significant chance that I'm doing something silly / wrong with the library and not understood how the code's working.  Here is an example which shows the behaviour:

```
const BSON = require('bson');
const bson = new BSON();

docs = [
  { foo: "bar" },
  { foo: "baz" },
  { foo: "quux" },
]

// Serialize the test data
serializedDocs = []
for (i = 0; i < docs.length; i++) {
  serializedDocs[i] = bson.serialize(docs[i])
}
buf = Buffer.concat(serializedDocs)

// The following are all fine
bson.deserialize(buf.slice(0, 18))
bson.deserialize(buf.slice(18, 36))
bson.deserialize(buf.slice(36, 55))

parsedDocs = []
// This is not happy: `Error: corrupt bson message`
bson.deserializeStream(buf, 0, docs.length, parsedDocs, 0)
console.log({parsedDocs})
```

It behaves as expected if you remove `buffer.length !== size` from the line mentioned above.  I'm hesitant to open a PR because maybe there's a reason it's been changed and I'm just using it wrong?

There's no rush from my perspective, I've got a workaround but I thought it might be good to point out.  Thanks for your help.

Ben

**Comment by jdelman** [comment]
@bewt85 Do you have a fork with a fix up somewhere? Would love to use this.

**Comment by bewt85** [comment]
Hi Josh,

I've hesitated making a PR because I don't understand the code well enough
to know what else this might break (and I only needed it to make some test
data so probably won't get round to understanding it properly).

That said, things seemed to work ok in the example code as soon as I
deleted `buffer.length !== size || ` from this line:
https://github.com/mongodb/js-bson/blob/2.0.0/lib/bson/parser/deserializer.js#L27

If I were you, I'd wait for someone who knows the code a bit better before
trying that though.

Ben

**Comment by daprahamian** [comment]
@bewt85 Thank you for bringing this to our attention. I should have a PR up shortly that addresses this issue.

**Comment by bewt85** [comment]
Thanks Dan
