### ISSUE TITLE
Can deserialize in browser but not in Node.Error: Invalid UTF-8 string in BSON document

### ISSUE THREAD

**Issue by RatedDS** [mongodb/js-bson#246]
I have some BSON serialized data that I'm sending as an ArrayBuffer to a WebSocket server.Testing it from the browser it is deserialized correctly, but in node I keep getting "Error: Invalid UTF-8 string in BSON document":

![image](https://user-images.githubusercontent.com/14005823/39962100-81a11c86-5645-11e8-931a-0ccac3829d82.png)

In Node:

`socket.on('message', function recibido(mensaje) {`
`                var bson = new BSON();`
`               var bufer = Buffer.from(mensaje);`
`                bson.deserialize(bufer);`
`}`

![image](https://user-images.githubusercontent.com/14005823/39962122-184b98b4-5646-11e8-9c11-4f558f00decf.png)

**Comment by daprahamian** [comment]
@RatedDS Can you confirm the following:

1. Your node version / browser
2. The version of the BSON library you are using in the browser and in node
3. If you can serialize / deserialize a value properly in Node

**Comment by RatedDS** [comment]
Sorry, I think the document did indeed have some invalid UTF-8.Closing this.
