### ISSUE TITLE
Node 10 DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by DominusVilicus** [mongodb/js-bson#248]
```
/**
* Converts to a string representation of this Id.
*
* @return {String} return the 24 byte hex string representation.
* @ignore
*/
ObjectID.prototype.inspect = ObjectID.prototype.toString;
```

How do you fix this issue, is there another way to allow custom inspection functions?

**Comment by BridgeAR** [comment]
Custom inspect was indeed recently removed. I just wanted to go ahead and fix that but I do not see how to do that right now without calling `require('util')`. That is necessary to get the currently used symbol.

**Comment by BridgeAR** [comment]
Refs #251

**Comment by DominusVilicus** [comment]
Thanks, this happens when you console.log an ObjectID

**Comment by mbroadst** [comment]
merged, thanks!
