### ISSUE TITLE
`ObjectID.generate()` Creates inconsistent process IDs if `process` is unavailable

### ISSUE THREAD

**Issue by juuxstar** [mongodb/js-bson#271]
When `process` is `undefined`, `ObjectID.prototype.generate()` makes a new, random pid value on each invocation [Line 155](https://github.com/mongodb/js-bson/blob/v3.0.2/lib/bson/objectid.js#L155).

Generating multiple ObjectIDs in this situation has each with a different value for it's 2 byte process ID component, which can cause the order of the IDs to be incorrect, in contradiction to the [spec](https://docs.mongodb.com/manual/reference/bson-types/#objectid)

I believe moving the pid retrieval/generation to be a file-level constant like MACHINE_ID should fix this issue.

**Comment by mbroadst** [comment]
Hi @juuxstar. You are correct that this is less than ideal, and should be changed. The actual location of the spec we should be conforming to is [here](https://github.com/mongodb/specifications/blob/master/source/objectid.rst), in the drivers specification repository, and there is already a JIRA ticket to track this [here](https://jira.mongodb.org/browse/NODE-1586). Please track the JIRA ticket for progress on this, thank you!
