### ISSUE TITLE
Error 'Invalid UTF-8 string in BSON document' when deserializing a previously serialized BSON document

### ISSUE THREAD

**Issue by bvanreeven** [mongodb/js-bson#277]
The following code throws an error on the `bson.deserialize(...)` call:

```javascript
const BSON = require("bson");
const bson = new BSON();

const offendingString = String.fromCharCode(0x41, 0x42, 0xFFFD, 0x43, 0x44); // "AB�CD"

const serialized = bson.serialize({ "value": offendingString });
const deserialized = bson.deserialize(serialized);
```

The error that is thrown is 'Invalid UTF-8 string in BSON document'. From [the source](https://github.com/mongodb/js-bson/blob/v3.0.2/lib/bson/parser/deserializer.js#L130) it appears that the `deserialize()` function specifically checks for the `0xFFFD` character and, if present, throws this error.

Why is a UTF-8 string containing this character considered invalid? And why doesn't `serialize()` already throw when serializing it in the first place? This seems like inconsistent behavior, in the sense that the BSON library allows you to serialize invalid data, but not deserialize it later, causing issues down the line when reading previously stored data.

**Comment by alex-sherwin** [comment]
This seems like a legit problem, does it not?

I ran across this with real data in a production system that contains this unicode character in some BSON documents.

In my case, I can explicitly use bson-ext instead, which does not exhibit this behavior, but using that over this package is painful when using TypeScript + Webpack for bundling a node app, native JavaScript packages are always easier to deal with.

**Comment by bvanreeven** [comment]
@daprahamian Thanks for the fix! 👍 

There seems to be another occurrence of this character here: https://github.com/mongodb/js-bson/blob/de42ea63ab07385ce1fb14d8a8d5360b8e36d8c8/lib/parser/deserializer.js#L562

Perhaps that one also needs the same fix?

**Comment by daprahamian** [comment]
Thanks for that @bvanreeven. See #286
