### ISSUE TITLE
ObjectId constructor with 12 character string argument form malfunction

### ISSUE THREAD

**Issue by croraf** [mongodb/js-bson#281]
There have been some similar issues open for this before (#106, #112), but I don't think they made the right point.
The issue happens indeed because the argument is not validated.

Providing `new ObjectId('000000000000')` gives the correct console.log of: `303030303030303030303030`.

Javascript strings are UTF-16 encoded. I create my ObjectId using:
`new ObjectId('ŽŽŽŽŽŽŽŽŽŽŽŽ')`
where Ž is this latin letter http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%C5%BD&mode=char

The construction doesn't fail, but while trying to console.log this ObjectId gives:
`undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined`

**Comment by daprahamian** [comment]
Hi @croraf,

What behavior are you expecting? Do you want this to error if a non-ASCII character is passed in?

**Comment by daprahamian** [comment]
Hi @croraf,

I created [NODE-1737](https://jira.mongodb.org/browse/NODE-1737) to track this. Closing the issue for now in favor of the JIRA ticket.

- Dan
