### ISSUE TITLE
Properties which are mongodb.ObjectId were not serialized

### ISSUE THREAD

**Issue by shaunxu** [mongodb/js-bson#289]
In the code below

```
const mongodb = require('mongodb');
const BSON = require('BSON');

const entity = {

    mongoObjectId: new mongodb.ObjectId(),

    bsonObjectId: new BSON.ObjectId(),

    name: "Shaun Xu"

};

const buffer = BSON.serialize(entity);
const output = BSON.deserialize(buffer);

console.log(JSON.stringify(output, null, 2));
```

I have two properties `mongoObjectId` which is `mongodb.ObjectId` and `bsonObjectId` which is `BSON.ObjectId`.

After I serialized and deserialize this object, I found the `mongoObjectId` was missed as below.

```
➜  bson-v4 node ./app.js
{
  "bsonObjectId": "5bf3ef74cada7ed148044e91",
  "name": "Shaun Xu"
}
```

This only happened when I upgrade to `bson@4.0`

**Comment by mbroadst** [comment]
thanks for the report, this is being tracked [in this ticket](https://jira.mongodb.org/browse/NODE-1769), and is fixed by #290.
