### ISSUE TITLE
in version 4.0 browser crashes with "Buffer.alloc" undefined error

### ISSUE THREAD

**Issue by iamdanthedev** [mongodb/js-bson#291]
Hello

I've just updated bson to v.4.0.0 in order to use EJSON feature, however it crashes the browser now and it looks like browser version has nodejs-related code leaking into:

![deepinscreenshot_select-area_20181123094633](https://user-images.githubusercontent.com/24467138/48932473-bfb4b980-ef04-11e8-8703-c958ff27e344.png)

**Comment by mbroadst** [comment]
@iamdanthedev can you please provide a minimal test case reproducing this?
