### ISSUE TITLE
Library Not Compiling With Angular: Global Is Not Defined. 

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/js-bson#301]
I have an Angular Application where I am using the Stitch client. I am trying to use the JS-BSON library and it seems like it is not available. 

I first added a link to the **"bson.bundle.js"** file inside teh scripts block provided in the angular.json file. The error I get is "bson.bundle.js:3761 Uncaught ReferenceError: global is not defined" . 

Any tips on how to get this to work?

**Comment by mbroadst** [comment]
Hi @saniyusuf, sorry for the shuffle but can you please open this ticket against the [stitch JS sdk](https://github.com/mongodb/stitch-js-sdk)? That team is responsible for integration into various web frameworks, and will be better equipped to handle your problem.

**Comment by saniyusuf** [comment]
Hi @mbroadst I am using it with Stitch but the issue is the Js-bson library not being compiled by Angular with or without stitch. Is there a reason for this?

**Comment by mbroadst** [comment]
We publish bundled versions of the library for use in the web in a number of different formats. The issue you are running into is most likely that the version of the module that stitch is depending on is not compatible with how you are building your angular application. Again, please reach out to the stitch team, they are experts in building these types of web applications and are better equipped to help with these issues.

**Comment by henry-bettany** [comment]
Add the following to your polyfills.ts file:
`(window as any).global = window;`

From [here](https://github.com/auth0/auth0.js/issues/753#issuecomment-386703094).

**Comment by saniyusuf** [comment]
Hi Guys,
This error is back now in 4.8.0. The same exact error I reported around a year ago.

**Comment by mbroadst** [comment]
Hi @saniyusuf! Can you please open a ticket on the [stitch repo](https://github.com/mongodb/stitch-js-sdk), it seems like there might be an issue with how they're bundling it. Additionally, we haven't had any bug reports along these lines in over a year (since your report indeed), so I'm wondering if there is something special in your case?

**Comment by saniyusuf** [comment]
Looks like I was importing the Remote Library for types which are now made available by the browser SDK. I have gotten rid of the error for now. If anything comes up Ill be the first to tell you

**Comment by fasidOnGit** [comment]
The issue persists in a web-worker. I added a `polyfills.worker.ts` and added it in the `tsconfig.worker.json`

```
// polyfills.worker.ts

// tslint:disable-next-line: no-any
(self as any).global = self;
// tslint:disable-next-line: no-any
(self as any).process = self;
// tslint:disable-next-line: no-any jsdoc-format
(self as any).process.on = (event, cb) => {/** empty **/};
// tslint:disable-next-line: no-any
(self as any).process.env = '';
// tslint:disable-next-line: no-any
(self as any).process.browser = true;
// tslint:disable-next-line: no-any
(self as any).process.version = '';
// tslint:disable-next-line: no-any
(self as any).process.versions = {node: false};

/**
 * Global.
 */
// tslint:disable-next-line: no-any
declare var global: any;
// tslint:disable-next-line: no-var-requires
// global.Buffer = global.Buffer || require('buffer').Buffer;
global = self;

```

**Comment by fasidOnGit** [comment]
I think I found the problem,
https://github.com/mongodb/js-bson/blob/616665f5e6f7dd06a88de450aaccaa203fa6c652/src/parser/utils.ts#L80

We either need to switch to using `globalThis` (which has pretty good support) or, just change the expressions to use `&&`, so that will become,
`if (typeof window === 'undefined' && typeof self === 'undefined') {`
