### ISSUE TITLE
ObjectID (capital "D") instances can't be serialized to Extended JSON

### ISSUE THREAD

**Issue by justingrant** [mongodb/js-bson#303]
The EJSON serializer: in 4.0.1 doesn't correctly serialize instances of ObjectID (capital "D") used by the official`'mongodb'` package. For example, running `EJSON.serialize` on the output of `db.coll.findOne()` will throw an exception. 

I'm working on a PR including new test cases.

BTW, this only affects the Extended JSON serializer. The BSON serializer was covered in #290.

**Comment by justingrant** [comment]
Hi @mbroadst - This issue was also closed by mistake. Do you want to re-open?

**Comment by mbroadst** [comment]
@justingrant ah hm, I guess it was auto-closed because of the commit message!
