### ISSUE TITLE
Contrary to its name, BSON is not in fact binary JSON

### ISSUE THREAD

**Issue by DrPizza** [mongodb/js-bson#319]
BSON encodes arrays as if they were objects with integer values for keys. Per the spec, `['red', 'blue']` is encoded as `{ '0': 'red', '1'; 'blue' }`. The array-ness is resurrected for nested arrays by dint of the `BSON_DATA_ARRAY` decoder passing `true` for `isArray` when making the recursive call, which in turn means that the holding object into which values are placed [is an array, not an object](https://github.com/mongodb/js-bson/blob/master/lib/parser/deserializer.js#L99).

Nothing in the BSON spec, so far as I can tell, precludes the use of an array as the root object. JSON does not preclude the use of an array as the root object; from [RFC 7159](https://tools.ietf.org/html/rfc7159), we have the productions "`JSON-text = ws value ws`" (where ws is whitespace), and "`value = false/null/true/object/array/number/string`", thus, arrays can be the root object. The second example of valid JSON objects in the RFC makes this explicit. BSON as a binary encoding of JSON therefore should allow arrays as the root element.

Problem is, nowhere does the arrayness of the root document get encoded. The holding object of the root document is always `{}`, never `[]`. Thus, `BSON.deserialize(BSON.serialize([]))` yields not the `[]` that one would expect from round tripping, but instead `{}`. `BSON.deserialize(BSON.serialize([1, 2, 3]))` produces not `[1, 2, 3]` but instead `{0: 1, 1: 2, 2: 3}`.

Other valid JSON objects include a naked integer. This does not round trip either: `BSON.deserialize(BSON.serialize(1))` yields `{}` (the information about the integer is discarded entirely). `BSON.deserialize(BSON.serialize(true))` is similarly obliterated.  `BSON.deserialize(BSON.serialize('string'))` is mishandled in the way one would expect from the other mishandlings: `{0: "s", 1: "t", 2: "r", 3: "i", 4: "n", 5: "g"}`.

BSON is, contrary to its name and reasonable expectation, not in fact a binary encoding of JSON, nor even a binary encoding of a superset of JSON. JSON permits these objects. BSON not only does not permit them--it silently destroys them, giving no indication that it is incompatible with them, and no indication that it has lost data.

Possible fixes would be some combination of:
1. Rename the project and change the website to make clear that BSON is not in fact "Binary JSON". Update the spec to make clear that the root document must be an object and cannot be an array or any primitive.
2. Fix the encoding so that the root element is encoded explicitly rather than has its type assumed to be object. There's no obvious backwards compatible way of doing this, except perhaps you could add an extra field that denotes "discard the root document and use its first child as if it were the true root"; since the first child of the root document has its type properly encoded then this should allow proper round-tripping.
3. Change the serializer so that it throws an exception when anything other than a non-array object is passed in.
4. As a crude hack: if the root object has only numeric keys that conform to JavaScript's array index type (any uint32 value, aside from 0xffffffff which is reserved and cannot use used as an array index) rewrite it to be an array. If as an additional constraint it only has contiguous indices that start at zero, and each element of the array is a single character, then it's probably a string, but might not be.

**Comment by mbroadst** [comment]
The BSON specification has the following production:
```
document ::= int32 e_list "\x00" 
e_list ::= element e_list
element ::= "\x04" e_name document  // Array
// many other element types

// much lower on the page
Array - The document for an array is a normal BSON document with integer values for the keys, starting with 0 and continuing sequentially. For example, the array ['red', 'blue'] would be encoded as the document {'0': 'red', '1': 'blue'}. The keys must be in ascending numerical order.
```

This precludes the use of an array as the root object. Documents are always lists of key-value pairs, and arrays are always encoded as maps from index -> value. This rules out option 2. Option 1 is not an option either. 

I think options 3 or 4 sound like the most reasonable approaches to consider. Thanks for your issue, I've created [NODE-192](https://jira.mongodb.org/browse/NODE-1921) to track this.

**Comment by DrPizza** [comment]
The `$$single$$` approach is the kind of thing I had in mind for option 2. Create a synthetic containing object for the naked value, along with some indication that it should be discarded at deserialization time. The use of in-band signalling is a little irksome (what if someone wanted to name a field `$$single$$` but have it treated normally) but if a comparable approach is already used elsewhere then it may be tolerable.

**Comment by ppedziwiatr** [comment]
I've just spent few hours debugging issues with BSON top-level array deserialization in our app, finally found this issue...would be really nice if at least point 3. was implemented...

**Comment by nbbeeken** [comment]
@ppedziwiatr Sorry to hear that, I agree there's probably something we could do here to improve UX when something unusual is passed into the serializer. Point 3 as stated would be a breaking change so it would need to wait until we're ready for a major release, but it seems like a good approach. I've added bson-5.0.0 as the fix version to [NODE-1921](https://jira.mongodb.org/browse/NODE-1921) so we'll capture it when we're implementing that.

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
