### ISSUE TITLE
There is not bson.js in dist

### ISSUE THREAD

**Issue by NicoleRobin** [mongodb/js-bson#320]
I want to use bson.js in my browser, but after I followed the installation steps, there is no bson.js in the dist directory.
There are only 4 files, but when import them into the browser, will get an error. Please tell me what should I do, thank you for help.
`bson.browser.esm.js bson.browser.umd.js bson.bundle.js bson.esm.js`

**Comment by NicoleRobin** [comment]
I want to use bson.js in my browser, but after I followed the installation steps, there is no bson.js in the dist directory.
There are only 4 files, but when import them into the browser,  will get an error. Please tell me what should I do, thank you for help.
`bson.browser.esm.js
bson.browser.umd.js
bson.bundle.js
bson.esm.js`

**Comment by mbroadst** [comment]
Hi @NicoleRobin, depending on your requirements you should be able to import either `bson.browser.esm.js` or `bson.browser.umd.js` for browser support. If that doesn't work, can you please share the error you're seeing?

**Comment by storv** [comment]
@mbroadst hi. i met  the same scene, and the error was Buffer$8.alloc is not a function 

```
bson.browser.umd.js:5556 Uncaught TypeError: Buffer$8.alloc is not a function
    at bson.browser.umd.js:5556
    at bson.browser.umd.js:3
    at Object.<anonymous> (bson.browser.umd.js:6)
    at Object.6.buffer (bson.browser.umd.js:5886)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.38.bson (index.js:9)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
```

**Comment by mbroadst** [comment]
Hi @storv, can you please provide more details about how you are trying to use this library? What framework you are using, how it's being packaged, etc. Any more details will be helpful here.

**Comment by GrosSacASac** [comment]
The browser example in the readme assumes you are using rollup or webpack. We should write it explicitly.

Both bson.browser.esm.js and bson.browser.umd.js are not standalone files. Which is confusing since most JavaScript that have a dist folder have standalone files there.

The error means that Buffer and Long is undefined

**Comment by daprahamian** [comment]
Hi @GrosSacASac,

In the case where you are not using a bundler, and want a version of `bson` that includes `Buffer` and `Long`, you can use `dist/bson.bundle.js`. I have created https://jira.mongodb.org/browse/NODE-2058 to update the front page documentation to reflect this.

Closing for now, feel free to reopen / file an issue if you have additional questions.

- Dan
