### ISSUE TITLE
Incorrect binary data EJSON.stringify

### ISSUE THREAD

**Issue by JeromeDeLeon** [mongodb/js-bson#331]
Basically I wanted to stringify the binary data but doing so results in an invalid one.

Suppose EJSON is imported;

```js
function getEJSONString(data) {
  return EJSON.stringify(data);
}
```

That gives me wrong binary format and whenever I imported it in another database of MongoDB, the files is nowhere to be found.

I manage to do it using old library, but tried several things using the current library like using `serialize`, `deserialize` or combination of both, but still the the problem persists.

Using `mongodb-extended-json` library solves the problem.

```js
function getJSONString(data) {
  return EJSON.stringify(ejson.serialize(data));
}
```

Still this is an outdated library and it would be better if this can be solve using the current one.

Where did I go wrong here?

**Comment by daprahamian** [comment]
@JeromeDeLeon can you give an example of what you mean by "wrong binary format"?

**Comment by JeromeDeLeon** [comment]
I tried to export the MongoDB data manually with NodeJS.
I was using EJSON stringify only to stringify all documents from collections; however, I was getting binary string differs from the binary string in the database.

from the database:
`/9j/4AAQSkZJRgABAgAAZABkAAD/`...

What I got:
`w7/CxAMDBAXDw0PFxsUEBAUGxW`....

But somehow, I managed to successfully stringify it, using the following:

```js
function getJSONString(data) {
  const { EJSON } = BSON;

  const serializedData = BSON.serialize(data);
  const deSerializedData = BSON.deserialize(serializedData);
  const serializedEJSON = EJSON.serialize(deSerializedData);

  return EJSON.stringify(serializedEJSON);
}
```

Am I doing it wrong?

**Comment by JeromeDeLeon** [comment]
The setup is here:

I'm using a library that encapsulates handling mongodb.

MongoDB: 3.3.1
OS: Windows 10
bson: 4.0.2

I just connect to the mongdb and fetch that data and stringify it using EJSON.
The result is the same as above.

**Comment by JeromeDeLeon** [comment]
I just don't get it why I need to do the following:
BSON S > BSON DS > EJSON S > EJSON Stringify just to get the right result

**Comment by daprahamian** [comment]
@JeromeDeLeon Thank you for the system information. Everything I have done on my end does not surface this bug, so I need to see exactly what you are doing to figure out where the discrepancy is. Please provide a code snippet I can run so I can reproduce what you are seeing.

**Comment by JeromeDeLeon** [comment]
```js
const router = require("express").Router();
const mongodb = require("mongodb");
const { EJSON } = require("bson");
const fs = require("fs");

router.get("/", async (req, res) => {
  const uri = "DATABASE_URI";
  const ws = fs.createWriteStream("./sample.json");

  const client = await mongodb.MongoClient.connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const db = client.db();
  const collection = db.collection("COLLECTION_WITH_BINARY_DATA");
  const documents = await collection.find({}).toArray();

  ws.write(EJSON.stringify(documents));
  ws.end();

  res.send("Yes!");
});

module.exports = router;
```

**Comment by JeromeDeLeon** [comment]
What I got was binary base64 both but with different binary string.

**Comment by kambing86** [comment]
most likely because of this line is using `buffer.toString('binary')`
https://github.com/mongodb/js-bson/blob/master/lib/extended_json.js#L269

```
Binary: o => new Binary(o.value(), o.subtype),
```

https://github.com/mongodb-js/extended-json/blob/master/lib/modes/strict.js#L116
in here it was using base64

```
new bson.Binary(new Buffer(val.$binary, 'base64'), parseInt(val.$type, 16));
```

**Comment by kambing86** [comment]
@daprahamian any update on this?

I created a codesandbox to show the issue of the parse and stringify

https://codesandbox.io/s/mongodb-bson-issue-jl4td

**Comment by kambing86** [comment]
I believe the problem is because the older version of `bson` generates a Binary object that doesn't have the `toExtendedJSON` function, then reaching https://github.com/mongodb/js-bson/blob/cea186763527e4d3749a8234d335e9c395effe5b/lib/extended_json.js#L305

it will try to map using https://github.com/mongodb/js-bson/blob/cea186763527e4d3749a8234d335e9c395effe5b/lib/extended_json.js#L269

and leads to https://github.com/mongodb/js-bson/blob/cea186763527e4d3749a8234d335e9c395effe5b/lib/binary.js#L230

**Comment by kambing86** [comment]
still cannot find which line is causing the issue, but to reproduce the problem, just using
mongodb 3.4.1 (latest version now, which use bson 1.1.3)

and try to use bson 4.0.3 to stringify the `Binary` type

```js
function getJSONString(data) {
  const serializedData = serialize(data);
  const deSerializedData = deserialize(serializedData);
  const serializedEJSON = EJSON.serialize(deSerializedData);

  return EJSON.stringify(serializedEJSON);
}

const fsChunks = mainDb.collection('fs.chunks');
const doc = await fsChunks.findOne({ files_id: new ObjectID('5da98716d0c8bd09d40ae9f6') });
console.log(doc.data);
console.log(doc.data.toExtendedJSON);
console.log({
  doc,
  wrongStringify: EJSON.stringify(doc).substring(0, 1000),
  correctStringify: getJSONString(doc).substring(0, 1000),
});
```

result

```
Binary {
  _bsontype: 'Binary',
  sub_type: 0,
  position: 261120,
  buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 48 00 48 00 00 ff e1 00 58 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 02 01 12 00 03 00 00 00 01 00 01 ... 261070 more bytes>
}
```
```
undefined
```
```
{
  doc: {
    _id: 5da98716d0c8bd09d40ae9f7,
    files_id: 5da98716d0c8bd09d40ae9f6,
    n: 0,
    data: Binary {
      _bsontype: 'Binary',
      sub_type: 0,
      position: 261120,
      buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 48 00 48 00 00 ff e1 00 58 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 02 01 12 00 03 00 00 00 01 00 01 ... 261070 more bytes>
    }
  },
  wrongStringify: '{"_id":{"$oid":"5da98716d0c8bd09d40ae9f7"},"files_id":{"$oid":"5da98716d0c8bd09d40ae9f6"},"n":0,"data":{"$binary":{"base64":"w7/DmMO/w6AAEEpGSUYAAQEAAEgASAAAw7/DoQBYRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAMKHaQAEAAAAAQAAACYAAAAAAAPCoAEAAwAAAAEAAQAAwqACAAQAAAABAAAEAMKgAwAEAAAAAQAAAsKoAAAAAMO/w60AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQw5QdwozDmcKPAMKyBMOpwoAJwpjDrMO4Qn7Dv8OAABEIAsKoBAADASIAAhEBAxEBw7/DhAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgvDv8OEAMK1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMsKBwpHCoQgjQsKxw4EVUsORw7AkM2JywoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6woPChMKFwobCh8KIwonCisKSwpPClMKVwpbCl8KYwpnCmsKiwqPCpMKlwqbCp8KowqnCqsKywrPCtMK1wrbCt8K4wrnCusOCw4PDhMOFw4bDh8OIw4nDisOSw5PDlMOVw5bDl8OYw5nDmsOhw6LDo8Okw6XDpsOnw6jDqcOqw7HDssOzw7TDtcO2w7fDuMO5w7rDv8OEAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC8O/w4QAwrURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjLCgQgUQsKRwqHCscOBCSMzUsOwFWJyw5EKFiQ0w6Elw7EXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFl',
  correctStringify: '{"_id":{"$oid":"5da98716d0c8bd09d40ae9f7"},"files_id":{"$oid":"5da98716d0c8bd09d40ae9f6"},"n":0,"data":{"$binary":{"base64":"/9j/4AAQSkZJRgABAQAASABIAAD/4QBYRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEAKADAAQAAAABAAACqAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgCqAQAAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE'
}
```

**Comment by kambing86** [comment]
finally found the line that is causing the issue

https://github.com/mongodb/js-bson/blob/dc9c1bb284a6c08e07f14e700bdbfb0fd57e5a13/lib/binary.js#L43

where the buffer is a binary string from `o.value()`

https://github.com/mongodb/js-bson/blob/cea186763527e4d3749a8234d335e9c395effe5b/lib/extended_json.js#L269

should be using `Buffer.from(buffer, 'binary')`

hope it helps

**Comment by bajanam** [comment]
This issue is now tracked in: [NODE-3020](https://jira.mongodb.org/browse/NODE-3020), please continue all discussion there.  Thanks!
