### ISSUE TITLE
Incorrect binary data Decimal128.fromString 

### ISSUE THREAD

**Issue by typicalnerd** [mongodb/js-bson#334]
Hello. Decimal128.fromString is working incorrect, you can reproduce bug using negative numbers of pattern `0.00XX` :
```
bson.Decimal128.fromString('-0.0097').toString() // -0.0000
bson.Decimal128.fromString('-0.0011').toString() // -0.0000
```

Same numbers, but with different zero count will work:
```
bson.Decimal128.fromString('-0.00970').toString() // -0.00970
bson.Decimal128.fromString('-0.00110').toString() // -0.00110
bson.Decimal128.fromString('-0.00010').toString() // -0.00110
```
bson package version is `4.0.2`

**Comment by F1NYA** [comment]
In addition to this issue:
https://github.com/Automattic/mongoose/issues/8323#issuecomment-564630122

Same bug in package [bson-ext](https://github.com/mongodb-js/bson-ext)

**Comment by agolin95** [comment]
Tracked in Jira: https://jira.mongodb.org/browse/NODE-3021

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
