### ISSUE TITLE
Serializer does not allow non-string keys in Map object

### ISSUE THREAD

**Issue by grgr-dkrk** [mongodb/js-bson#356]
`Map` Object accepts a non-string value for the key, but it looks like the serializer doesn't allow it.

The code below causes an error:

```typescript
const mapObject = new Map()

mapObject.set({foo: 'bar'}, 'foo')
mapObject.set(undefined, 'foo')
mapObject.set(NaN, 'bar')
mapObject.set(3, 'baz')
//-> Map (4) {{…} => "foo", undefined => "foo", NaN => "bar", 3 => "baz"}

// use MongoDB Node.JS Driver
await collection.insertOne({
  data: mapObject,
})
//-> TypeError: argument must be a string
```

Functions such as `serializeString` take a key as an argument, but it is uncertain whether the Map Object's key has a string, thus `buffer.write()` may raise a TypeError.

It can work around that by converting the key to a string and passing it in the `serializeInto`, but I don't know if that's a good way, as it easily causes duplicate keys.

**Comment by nbbeeken** [comment]
Hello @grgr-dkrk, unfortunately this type of support cannot be added to BSON: http://bsonspec.org/spec.html 
BSON is made up of a sequence of string keys mapped to a number of limited typed values, so not every type is permitted to be a key like es6 Maps allow.
