### ISSUE TITLE
Proper way to get Javascript object from loaded BSON file

### ISSUE THREAD

**Issue by mobileben** [mongodb/js-bson#357]
This is my first endeavor with BSON. I wanted to use this in an HTML 5 to store some of my game data. It is currently working with JSON.

The idea is to save it as BSON. I would either embed or load the file. Then convert this BSON into a Javascript object.

I use a Python script to create the data. This uses `pymongo`. A simple sample is:

```
data = { 'key0': 'a', 'key1': [ 1, 2, 3 ], 'key2': 'b' }
with open('test.bson', 'wb') as fp:
    encoded = bson.encode(data)
    fp.write(encoded)
```

The file `test.bson` is then loaded in Javascript with either `XMLHttpRequest` or is embedded via `raw-loader`.

However I cannot figure out how to use the library to take convert this file into a Javascript object. Any attempt results in various errors from buffer size issues, needing to convert to `Buffer`, or some exception being thrown.

I create a repo here: https://github.com/mobileben/test-bson-js.

This contains the test data.

Note that I can decode the file in Python as well as use `bsondump` to dump the file.

It's not clear to me why on the JS side it cannot take the same data and decode.

**Comment by mobileben** [comment]
I did post an SO question on this. https://stackoverflow.com/questions/61448282/converting-bson-data-saved-in-file-to-javascript-object?noredirect=1#comment108700819_61448282

I've discovered that there seems to be a couple of issues.

If I have an array of objects, some cases cause it to result in an `Uncaught error` during deserialization. 

Also when floats are decoded, the values are wrong. Integer values are fine.

Note that `bsondump` works for both these cases.

**Comment by dislick** [comment]
I have the same issue, `bsondump` works fine but this library throws `Error: buffer length 11698 must === bson size 47`.

**Comment by mbroadst** [comment]
@mobileben sorry we missed your report, we don't generally use GitHub issues for bug reports (they are open right now because we don't want to lose any previously existing reports we're trying to resolve). Can you please open a [JIRA ticket](jira.mongodb.org/projects/NODE) for this?

**Comment by mobileben** [comment]
@mbroadst Sorry for the delay on this. That link is 404. I assume this is the right one? https://jira.mongodb.org/projects/NODE

It is asking me to login though. Is there anyway I can create one without having to create yet another account? It looks like it would be having me create an account for mongodb.com.

**Comment by bajanam** [comment]
If this is still an issue, please do create an account on the link above.  Thanks!
