### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by 0xAozora** [mongodb/js-bson#367]
Since version 4.0.1 dist/bson.bundle.js fails to load in the browser.

![image](https://user-images.githubusercontent.com/12783903/83701581-5853eb80-a60a-11ea-8dbe-e72579f5b9fe.png)

**Comment by nbbeeken** [comment]
Just for reference we use [JIRA](https://jira.mongodb.org/projects/NODE) to track our issues and prefer that issues are submitted there so we can better prioritize them.
Thanks for submitting! resolved in PR #404
