### ISSUE TITLE
[Types] allow access to ObjectID binary buffer

### ISSUE THREAD

**Issue by erfanium** [mongodb/js-bson#375]
In Typescript, I can't access to `id` property of ObjectID, because it's not defined in index.d.ts file:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e9a166498581d3bf3984db7611ce95e3e0cd7dd6/types/bson/index.d.ts#L358

```ts
const a = new ObjectID();
a.id // Error
```

**Comment by nbbeeken** [comment]
We will be releasing our own type definitions soon, that will resolve this issue if you are able to upgrade. If you need this to work on your current version of the bson lib then you need to submit an issue/pr to DefinitelyTyped.

Just for reference we use [JIRA](https://jira.mongodb.org/projects/NODE) to track our issues and prefer that issues are submitted there so we can better prioritize them.
Thanks for submitting! resolved in PR #388
