### ISSUE TITLE
UMD version failed to load

### ISSUE THREAD

**Issue by Jack-Works** [mongodb/js-bson#378]
> Uncaught TypeError: Cannot read property 'prototype' of undefined
> 
>    at bson.browser.umd.js:160
> 
>    at bson.browser.umd.js:4
> 
>    at bson.browser.umd.js:5

![](https://user-images.githubusercontent.com/5390719/89118844-a76baf00-d4db-11ea-9a70-68a4fda2d7d3.png)

**Comment by nbbeeken** [comment]
Just for reference we use [JIRA](https://jira.mongodb.org/projects/NODE) to track our issues and prefer that issues are submitted there so we can better prioritize them.
Thanks for submitting! resolved in PR #404
