### ISSUE TITLE
Please stop using __proto__ to set prototype

### ISSUE THREAD

**Issue by Jack-Works** [mongodb/js-bson#380]
Deno doesn't support the `__proto__` hack. ( `__proto__` is defined in the Annex B of ES spec so only browsers must implement this.)

Please use Object.setPrototypeOf() as alternative.

![](https://user-images.githubusercontent.com/5390719/89119603-38de1f80-d4e2-11ea-9237-c486ea4805bd.png)

**Comment by Jack-Works** [comment]
Also, NodeJS have an option to disable `__proto__` to improve security.

nodejs/node@b598321

**Comment by nbbeeken** [comment]
Just for reference we use [JIRA](https://jira.mongodb.org/projects/NODE) to track our issues and prefer that issues are submitted there so we can better prioritize them. 
Thanks for submitting! resolved in PR #404

**Comment by Jack-Works** [comment]
@nbbeeken hi, how does it resolved in #404? I don't see a related code change in that PR!

**Comment by nbbeeken** [comment]
`__proto__` usage was being produced by our build system which has been updated in that PR and it no longer produces code that uses that style of code. The changes will be published in the next release.
