### ISSUE TITLE
`Long` integers are is not serialized as LONG

### ISSUE THREAD

**Issue by marcj** [mongodb/js-bson#384]
Current [code](https://github.com/mongodb/js-bson/blob/master/lib/parser/serializer.js#L47) in serialize.js has following check:

```javascript
    if (
        Math.floor(value) === value &&
        value >= constants.JS_INT_MIN &&
        value <= constants.JS_INT_MAX
    ) {
      if (value >= constants.BSON_INT32_MIN && value <= constants.BSON_INT32_MAX) {
          // Set int type 32 bits or less
      } else if (value >= constants.JS_INT_MIN && value <= constants.JS_INT_MAX) {
          // Encode as double
      } else {
          // Set long type
      }
    } else {
        // Encode as double
    }
```

The code path to `Set long type` is will never be reached since the initial `if` condition already filters it out. Thus when trying to serialize currently values like `9007199254741002` (which is greater than `JS_INT_MAX`) it will be serialized as double instead of long.

**Comment by emadum** [comment]
Hi @marcj, we've confirmed this is an issue and created a [JIRA ticket](https://jira.mongodb.org/browse/NODE-2769) to track it. Thanks for the report!
