### ISSUE TITLE
 deserialized long

### ISSUE THREAD

**Issue by NotDark** [mongodb/js-bson#387]
after deserialize bson

how i can get the value like 637333521425874410 not
key: Long { low: 126024328, high: 148390332, unsigned: false },

**Comment by mbroadst** [comment]
If the long is small enough to fit into a `number` then you can call `.toNumber()` on the `Long` instance.

This issue tracker is for bug reports only, please consider using our [community forums](https://developer.mongodb.com/community/forums/tags/c/drivers-odms/7/node-js/) for these types of questions in the future.
