### ISSUE TITLE
ObjectId.isValid counts all numbers as valid values which is wrong

### ISSUE THREAD

**Issue by ioncreature** [mongodb/js-bson#391]
I've faced strange behaviour in my test suite:

```js
ObjectId.isValid(1); // returns true
```
And got cast error on mongoose side trying to insert this id: `Cast to ObjectId failed for value "1" at path "participants" for model "Chat"`

Here is the code which makes this happen:
https://github.com/mongodb/js-bson/blob/bdc046ff3ccd7b5ff8ec9995645cd1f9c81693b7/src/objectid.ts#L328-L330

Can we get rid of it since javascript numbers aren't valid ObjectIds?

Thanks.

**Comment by agolin95** [comment]
https://jira.mongodb.org/browse/NODE-3034

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
