### ISSUE TITLE
deserializer does not handle fields named __proto__

### ISSUE THREAD

**Issue by davidje13** [mongodb/js-bson#420]
**BSON Version:** 4.2.2

When deserializing BSON, any field named `__proto__` will attempt to set the special `__proto__` property, rather than add an enumerable property to the object.

This is because there are no checks on the `object[name]` property assignment in multiple locations here: https://github.com/mongodb/js-bson/blob/master/src/parser/deserializer.ts#L177

This is not in itself a security issue (there is no risk of modifying the global object prototype), but leads to inconsistent behaviour if an object with an enumerable `__proto__` field is serialised.

For example:

```js
const BSON = require('bson');

const original = JSON.parse('{"__proto__": {"foo": "bar"}}');
console.log(original);                     // { __proto__: { foo: 'bar' } }
console.log(original.foo);                 // undefined

const serialised = BSON.serialize(original);
const deserialised = BSON.deserialize(serialised);
console.log(deserialised);                 // {}
console.log(deserialised.foo);             // bar
```

**Comment by agolin95** [comment]
https://jira.mongodb.org/browse/NODE-3153
