### ISSUE TITLE
Possible perf improvement ?

### ISSUE THREAD

**Issue by billouboq** [mongodb/js-bson#453]
I was wondering if it could improve performance to use allocateUnsafe instead of allocate ?
Since we are filling that buffer right away I guess it is "safe" to use the unsafe version of it, what do you think ?

https://github.com/mongodb/js-bson/blob/2330ab1274166c285cbd8a0c3eff5a52573cf34d/src/parser/deserializer.ts#L192

**Comment by dariakp** [comment]
Hi @billouboq thank you for the suggestion! I created a corresponding ticket in jira [NODE-3557](https://jira.mongodb.org/browse/NODE-3557) so that we can discuss this with the team in an upcoming triage meeting.

**Comment by dariakp** [comment]
@billouboq Just wanted to give you an update - we added your suggestion for consideration in our BSON improvements epic, we have a number of related issues to how we handle buffer encoding/decoding in general, so these will all likely get tackled together. Do you mind if I close this github issue in favor of just tracking NODE-3557, or would you rather this stay open until we schedule the work?

**Comment by billouboq** [comment]
You can close it of course, thanks for the update ! 🙏

Le lun. 23 août 2021 à 18:52, Daria Pardue ***@***.***> a
écrit :

**Comment by dariakp** [comment]
Great, thanks again!
