### ISSUE TITLE
Stop depending on buffer?

### ISSUE THREAD

**Issue by jimmywarting** [mongodb/js-bson#456]
`node:buffer` is a NodeJS only feature and bundeling it into Deno and Browser is often bloated, i where wondering if you could replace all of it with eg: TextEncoder/decoder, DataView Uint8Array, ArrayBuffer.isView etc.

If not could you at least use nodes builtin buffer instead? `require('node:buffer')` this will ensure that we always get the latest version of node's Buffer that anyone would expect. the built in is faster than a ponyfill

**Comment by nbbeeken** [comment]
Hi @jimmywarting thanks for the suggestion! I recently filed [NODE-3555](https://jira.mongodb.org/browse/NODE-3555) which is along the lines of what you suggest. In future efforts we want to make our BSON lib work on any JS platform if possible. However there is some concerns around performance degradation when using ArrayBuffer APIs, so it will need some investigating. In terms of the require, when using Node.js the native buffer is imported. We can't change the import to use `node:buffer` because it break the bundled web builds that do need the ponyfill.

**Comment by jimmywarting** [comment]
fyi, there is quite huge performance degradation when using `buf.toString()` and also using nodes `string_decoder` compared to just using built in TextDecoder.

ref: https://github.com/nodejs/node/issues/39301#issuecomment-877626152

quite important to test out what is run natively in browser and also as a polyfill in browsers and Deno

**Comment by nbbeeken** [comment]
Here's a benchmark I put together:
```javascript
const Benchmark = require('benchmark')
const fetch = require('node-fetch')
const {TextDecoder} = require('util')
const suite = new Benchmark.Suite;

const decoder = new TextDecoder('utf8', {fatal: true})

fetch('https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html')
.then(response => response.arrayBuffer())
.then(arrayBuffer => {

    const largeBuffer = Buffer.from(arrayBuffer, 'utf8');
    const smallBuffer = Buffer.from('ℕ ⊆ ℕ₀ ⊂ ℤ ⊂ ℚ ⊂ ℝ ⊂ ℂ, ⊥ < a ≠ b ≡ c ≤ d ≪ ⊤ ⇒ (A ⇔ B),', 'utf8');

    console.log(`downloaded utf8: ${largeBuffer.byteLength} bytes`)
    console.log(`small exmp utf8: ${smallBuffer.byteLength} bytes`)

    suite
    // LARGE
    .add('large Buffer toString', function () {
        largeBuffer.toString()
    })
    .add('large TextDe decode  ', function () {
        decoder.decode(largeBuffer)
    })
    // SMALL
    .add('small Buffer toString', function () {
        smallBuffer.toString()
    })
    .add('small TextDe decode  ', function () {
        decoder.decode(smallBuffer)
    })
    // EVENTS
    .on('cycle', function (event) {
        console.log(String(event.target));
    })
    .on('complete', function () {
        console.log(`Fastest is ${this.filter('fastest').map('name')}`);
    }).run()
}).catch(e => {
    console.log(e)
    process.exit(1)
})
```
And here's the results I get
```
downloaded utf8: 13737 bytes
small exmp utf8: 96 bytes
large Buffer toString x 13,435 ops/sec ±0.62% (93 runs sampled)
large TextDe decode   x 25,839 ops/sec ±0.83% (93 runs sampled)
small Buffer toString x 1,871,376 ops/sec ±0.54% (96 runs sampled)
small TextDe decode   x 312,321 ops/sec ±7.32% (49 runs sampled)
Fastest is small Buffer toString
```

It looks like TextDecoder is significantly slower on small inputs but it beats out Buffer#toString on large inputs. I would assume that the typical database usage is on average dealing with small string lengths (identifiers, addresses, etc.). However there may be room here for some optimization that could use different deserializers. That being said our library supports Node.js 6+, Chrome, Firefox, IE and React Native environments, I'm not sure that we can ensure best performance in all those environments.

I do however want to make sure we do a through investigation of this issue specifically so I have broken it out into its own ticket: https://jira.mongodb.org/browse/NODE-3566. We are going to be working on adding continuous perf measurement to our CI soon so addressing perf related issues should become easier going forward.

**Comment by jimmywarting** [comment]
I bet you that if you run the same benchmark in a non-NodeJS env that uses a "browserified" version using npms buffer module that it will be significant slower

**Comment by jimmywarting** [comment]
Did help you out in order to compare browsers versions: 
https://jsfiddle.net/dq6avnx5/1/

**Comment by erfanium** [comment]
@jimmywarting 
You can check this out
https://github.com/lucsoft/deno_bson
That's what you want, a javascript bson library that not depends on Buffer (and other node components)
