### ISSUE TITLE
MongoID incrementation is not future proof (wraps around at 16.7mln objects created per second)

### ISSUE THREAD

**Issue by Rush** [mongodb/js-bson#474]
It looks like JIRA is for internal use of mongodb.com - how is the community supposed to interact with this project? Is the community not welcome anymore? Anyhow I am leaving the below thoughts for your consideration.

Based on the code it looks like if more than 16mln (16777216 (2^24 - 5 bytes)) object ids are generated in one second, they will no longer be unique in this particular second as the counter will wrap around.

https://github.com/mongodb/js-bson/blob/master/src/objectid.ts#L149
https://github.com/mongodb/js-bson/blob/master/src/objectid.ts#L181

A solution would be to perhaps increment the process id when maximum value of the counter is detected.

You could say it's unlikely that 16mln object ids are generated in one second but as computers are getting faster it's not hard to imagine a database importer process that creates over 16mln objects in one second.

**Comment by nbbeeken** [comment]
Hi @Rush our [JIRA](https://jira.mongodb.org/projects/NODE/issues) is public, it does require you to sign up for an account to make a ticket but this is in the interest of making sure we can follow up with every issue submitted and it helps us stay organized.

If I understand correctly while the 3 byte counter may wrap around the Date.now() call is in a granularity of milliseconds which should suffice on preventing the logic here from creating colliding ObjectIds.

**Comment by Rush** [comment]
> If I understand correctly while the 3 byte counter may wrap around the Date.now() call is in a granularity of milliseconds which should suffice on preventing the logic here from creating colliding ObjectIds.

The timestamp part of ObjectId is 4 bytes and its granularity is in seconds, not miliseconds.

https://github.com/mongodb/js-bson/blob/master/src/objectid.ts#L159

**Comment by nbbeeken** [comment]
Ah yes you are entirely correct, overlooked the `/ 1000`! 🤦  
If you've run into this issue / have a use case for us, opening an issue on our JIRA is the best way to fit it in to the teams process.

**Comment by Rush** [comment]
All right. My motivation for creating the JIRA account is low. I am happy to just leave my thoughts for your consideration in here. If Mongo is not capable of inserting 16mlns of objects per second then it's probably a no issue. If it is capable, you can bet on encountering this issue at some point when somebody imports a big data collection into the DB via some piece of code. 

Think of this as a Y2K problem.

**Comment by nbbeeken** [comment]
Thanks for the insight, I think there's an interesting use case here that we may come across someday.
