### ISSUE TITLE
BSON Deserialization fails in PPC platform

### ISSUE THREAD

**Issue by gireeshpunathil** [mongodb/js-bson#73]
MongoDB connectivity test fails in PPC platform. The external manifestation is the error message: "Child document exceeds parent's bounds"

The reason is that the metadata pertinent to the connection is in little endian byte order, and the BSON library parses the data in that order. In big endian systems such as PPC, the deserialization helper methods such as ReadUInt32() returns wrong data (as the first byte in the stream is treated as the most significant byte and all scalar conversions fail).

Please, will you fix the multi-byte readers to cover the big endian systems as well?

**Comment by maximmai** [comment]
hi @christkv @gireeshpunathil 

I have a patch to address this issue, however, it's for the header file "bson.h" (https://github.com/meteor/js-bson/blob/master/ext/bson.h) in the native driver. 

Should I open an issue in the other repository and contribute the fix there?
